### ISSUE TITLE
Our own metrics examples do not scrape the Kafka Exporter

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2193] opened 2019-11-14 23:59 UTC
We added Kafka Exporter to provide addiitonal metrics. But it seems that our own example files for configuring the Prometheus operator and our docs do configure it to scrape these metrics. Based on a Slack discussion (https://cloud-native.slack.com/archives/CMH3Q3SNP/p1573775472031900), following option can help to scrape it:

```yaml
  additionalServiceMonitors:
    - name: "kafka-exporter"
      selector:
        matchLabels:
          strimzi.io/name: my-cluster-kafka-exporter
      namespaceSelector:
        any: true
      endpoints:
        - port: metrics
          interval: 10s
          path: /metrics
```

We should incorporate this into our examples and docs.

**Comment by scholzj** [comment] 2019-11-15 00:02
Unless we have any other Prometheus Operator guru, it would be great if @stanlyDoge can look at it. Thanks.

**Comment by stanlyDoge** [comment] 2019-11-26 12:58
With the current master I am getting kafka-exporter metrics without any modification in the example files. Is there any chance `kgib` (the guy from the slack) had no traffic in his cluster and thus the metrics were not available?

![Snímek z 2019-11-26 13-56-55](https://user-images.githubusercontent.com/19408098/69635464-bd73c680-1054-11ea-8f78-681e3d127c27.png)

**Comment by scholzj** [comment] 2019-11-26 13:10
Ask him on Slack.

**Comment by ppatierno** [comment] 2019-11-29 08:05
I did the same for my Strimzi on AKS demo and it seems to work fine. We should get in touch with that guy on Slack as Jakub suggested.

**Comment by stanlyDoge** [comment] 2019-11-29 08:54
I've already pinged him but no pong so far.

**Comment by stanlyDoge** [comment] 2019-12-03 15:38
We were not able to reproduce this. Closing.

**Closed by stanlyDoge** 2019-12-03 15:38 UTC
Labels: bug
