### ISSUE TITLE
[Bug]: Need Endpoint for health check

### ISSUE THREAD

**Issue by chandrasekhar2595** [strimzi/strimzi-kafka-operator#9511] opened 2024-01-05 19:53 UTC
### Bug Description

I am trying to add some health check endpoint to mirrormaker but I don't find any

### Strimzi version

main

### Kubernetes version

1.25

**Comment by scholzj** [comment] 2024-01-05 19:54
Duplicate of https://github.com/orgs/strimzi/discussions/9510

**Closed by scholzj** 2024-01-05 19:54 UTC
Labels: bug, needs-triage
