### ISSUE TITLE
ZooKeeper rolling update should deal with unready pods

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1001] opened 2018-10-18 08:34 UTC
Further to my comments on #969 I think there's an extra problem with how we're handling zookeeper rolling, based on what I've observed looking at Strimzi upgrading.

Even if the readiness is based on `stat` and looking for `leader`, `follower` (or `standalone`) in the output we can still break the cluster. The problem is that if there is a problem in the node that was restarted we wait for it to become read, but it doesn't and eventually the wait times out. On the next reconciliation we decide not to roll that pod based on the metadata and proceed to delete the next pod in the SS. If that fails to come back up the same timeout happens there too. Each reconciliation takes out another ZK pod until the whole cluster is down. At that point the Kafka brokers without any functioning zookeeper and the whole cluster grinds to a halt.

**Comment by scholzj** [comment] 2022-02-22 15:42
Triaged on 22.02.2022: We need to see if this can still reproduce or not. 

@tombentley Any chance you still know a scenario which can cause this?

**Comment by tombentley** [comment] 2022-03-03 14:34
Sorry, but I don't know. In the KafkaRoller we ended up ensuring that we always consider the unready pods first. I don't think we ever did anything similar for ZK, so hypothetically it's probably still a problem.

**Comment by scholzj** [comment] 2022-03-03 15:46
Ok, I did following test:
* Deployed Kafka cluster successfully
* Edited the ZooKeeper resources in the Kafka CR to some unrealistically high value
* Let the operator deal with it

=> with enough time, it rolled all 3 ZooKeeper pods to the Pending state. So this seems to be something we should fix. Marking it as a bug.

**Comment by robobario** [comment] 2022-10-03 08:21
I'm looking into this

**Closed** 2022-10-06 15:50 UTC
Labels: bug
