### ISSUE TITLE
[Enhancement]: Improvement of Resource Regeneration Due to `x-kubernetes-preserve-unknown-fields`

### ISSUE THREAD

**Issue by selenehyun** [strimzi/strimzi-kafka-operator#9291] opened 2023-10-25 08:46 UTC
### Related problem

The resources property of CRDs (Custom Resource Definitions) produced by the model managed in this project all include x-kubernetes-preserve-unknown-fields.
When I use this in conjunction with the terraform tool I'm using, it leads to a problem where Terraform destroys Kafka resources every time it needs to make changes to the resources property and then tries to add them again, resulting in the recreation of Kafka resources.

Simply changing the manifest and sequentially restarting Pods would suffice, but this process takes a long time to apply the changes.
Moreover, while Kafka resources are being recreated, the Kafka cluster becomes unusable.

I believed that to resolve this issue, CRDs needed to be modified, as this behavior is intentional in Terraform.

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1841#issuecomment-1254825692

### Suggested solution

To address this, my proposed idea was to make CrdGenerator explicitly define subproperties for the limits/requests properties of resources.
This way, Terraform can modify the resources property without recreating Kafka resources, allowing changes to be applied without the need for resource recreation.
However, I'm looking for better ideas to solve this issue!

### Alternatives

I also think that creating a separate model by inheriting from ResourceRequirements could be an alternative approach.

### Additional context

A simple code modification for this idea is similar to the following PR: https://github.com/strimzi/strimzi-kafka-operator/pull/9292

**Comment by scholzj** [comment] 2023-10-25 10:08
Duplicate of https://github.com/strimzi/strimzi-kafka-operator/issues/7985

**Closed by scholzj** 2023-10-25 10:08 UTC
Labels: enhancement, needs-triage
