### ISSUE TITLE
[Enhancement] using external promerheus for strimzi kafka jmx and other metrics collection instead of using promertheus on same kubernetes cluster

### ISSUE THREAD

**Issue by kvenu1458** [strimzi/strimzi-kafka-operator#6717] opened 2022-04-21 09:44 UTC
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

**To Reproduce**
2. Create Custom Resource '....'
3. Run command '....'

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: [e.g. main, 0.22.1]
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: [e.g. Kubernetes 1.20, OpenShift 4.7]
 - Infrastructure: [e.g. Amazon EKS, Minikube]

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh --namespace <string> --cluster <string> [--bridge <string>] [--connect <string>] [--mm2 <string>]`*

**Additional context**

**Comment by kvenu1458** [comment] 2022-04-21 09:48
currently as per Strimzi documentation we installed prometheus on same kubernetes cluster where strimzi kafka cluster setup, but using prometheus on same kubernetes cluster will consume space to store all jmx and other metrics, and it might lead to space issue.

So, we want to avoid installing Prometheus on same kubernetes cluster and want to utilze outside Prometheus and collecting jmx metrics and all other metrics

**Comment by scholzj** [comment] 2022-04-21 13:04
Duplicate of #6718

**Closed by scholzj** 2022-04-21 13:04 UTC
Labels: question
