### ISSUE TITLE
 Standard custom image registration plug-in failed

### ISSUE THREAD

**Issue by gaozuo** [strimzi/strimzi-kafka-operator#9566] opened 2024-01-18 08:40 UTC
### Bug Description

I started a topic and the relevant information has been written in, please check: https://github.com/orgs/strimzi/discussions/9565

### Strimzi version

quay.io/strimzi/operator:0.39.0

### Kubernetes version

v1.27.4+k3s1

**Comment by scholzj** [comment] 2024-01-18 08:41
Duplicate of #9565. Please do not open a bug and discussion at the same time!

**Closed by scholzj** 2024-01-18 08:41 UTC
Labels: bug, needs-triage
