### ISSUE TITLE
[Bug]: Strimzi cluster operator not creating StrimziPodSet/Zookeeper/Kafka 

### ISSUE THREAD

**Issue by bmanuel1974** [strimzi/strimzi-kafka-operator#9247] opened 2023-10-16 14:29 UTC
### Bug Description

Strimzi cluster operator gets stuck and will not provision new StrimziPodSet

This only seems to happen in our development clusters where we are managing 48 different Kafka clusters in 48 different namespaces.  These are all small clusters with either 1 or 3 nodes.  
On occasion if you do a new installation of kafka, the Kafka custom resource gets created, but zero events show up on the resource and the operator does not reconcile it.  The operator does continue to work and cycle through the namespaces, but will never create the StrimziPodSet unless it is restarted.

We are restarting the operator sometimes 2-3 times per day.

I have tried waiting for a while, but you can see the operator try to reconcile the namespace and then just move on to another one without errors.

It sounds like uninstalling via helm might be causing this problem.  These development environments often are being uninstalled and reinstalled in a short time period.  

```
2023-10-16 17:06:35 INFO  AbstractOperator:265 - Reconciliation #2325(watch) Kafka(default/kafka): Kafka kafka will be checked for creation or modification
2023-10-16 17:06:35 INFO  AbstractOperator:537 - Reconciliation #2322(watch) Kafka(default/kafka): reconciled
2023-10-16 17:06:36 INFO  AbstractOperator:511 - Reconciliation #2330(watch) Kafka(default/kafka): Kafka kafka in namespace default was DELETED
2023-10-16 17:07:28 INFO  AbstractOperator:511 - Reconciliation #2365(watch) Kafka(default/kafka): Kafka kafka in namespace default was ADDED
2023-10-16 17:07:35 INFO  AbstractOperator:400 - Reconciliation #2325(watch) Kafka(default/kafka): Reconciliation is in progress
2023-10-16 17:08:35 INFO  AbstractOperator:400 - Reconciliation #2325(watch) Kafka(default/kafka): Reconciliation is in progress
```

### Strimzi version

0.37.0

### Kubernetes version

1.23.17

### Installation method

Helm chart

### Infrastructure

Amazon EKS
We are using Karpenter to provision spot instances.

**Comment by scholzj** [comment] 2023-10-19 08:26
Discussed on the Community call on 19.10.2023: Please provide the full operator logs. Without that, it is not clear what the problem is.

**Comment by scholzj** [comment] 2023-10-19 14:55
The DEBUG log level is normally the best. But even without it, the full log will be a start.

**Comment by bmanuel1974** [comment] 2023-10-20 00:38
Logs for stuck operator:
[stuck.txt](https://github.com/strimzi/strimzi-kafka-operator/files/13048716/stuck.txt)

Logs after a restart:
[after-restart.txt](https://github.com/strimzi/strimzi-kafka-operator/files/13048717/after-restart.txt)

The namespace that was stuck at the time: `141b6121c893dc2b6ca9da0a1c6a23d5`

**Comment by scholzj** [comment] 2023-10-20 09:19
Your log is not complete - it does not start from the beginning, so it is a bit hard to see the configuration, how many resources you actually have there and other things. 

The reconciliation of the Kafka resource in namespace `141b6121c893dc2b6ca9da0a1c6a23d5` seems to be stuck way before it starts. It has clearly nothing to do with the other problem you linked this to. The stuck reconciliation is likely caused by some unhandled exception caused by one of the many Kubernetes API errors you get. A DEBUG level log might help us to show where exactly it is and help us handle it. But it would need to be complete and contain the moment when it gets stuck and not like this log where it is already stuck.

I don't know if you actually tried to look into the logs, but it also contains huge amount of events. It is less then 10 minutes long but has over 4300 events when the Kafka resource was modified. This seemed to have happened over 4331 unique custom resources. Is that really the scale you run it at? Was this some intentional modification? In any case, I think that is likely to overload all kind of things ... the operator, the Kube APIs etc. I guess this is the reason for the Kube API errors we see and which ultimately cause the stuck reconciliation issue.

**Comment by Elyytscha** [comment] 2023-11-02 18:30
i have the same issue, cant install any kafka clusters due to this with gke kube v1.25

```
2023-11-02 18:28:07 ERROR StrimziPodSetController:409 - Reconciliation #3(watch) StrimziPodSet(core-graphql-hive/graphql-hive-kafka-zookeeper): StrimziPodSet graphql-hive-kafka-zookeeper in namespace core-graphql-hive reconciliation failed
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129) ~[io.fabric8.kubernetes-client-api-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122) ~[io.fabric8.kubernetes-client-api-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:44) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:1142) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:97) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.strimzi.operator.cluster.operator.assembly.StrimziPodSetController.maybeCreateOrPatchPod(StrimziPodSetController.java:470) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.operator.assembly.StrimziPodSetController.reconcile(StrimziPodSetController.java:398) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at io.strimzi.operator.cluster.operator.assembly.StrimziPodSetController.run(StrimziPodSetController.java:566) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: request timed out
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:340) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:753) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:97) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42) ~[io.fabric8.kubernetes-client-6.9.0.jar:?]
        ... 6 more
Caused by: java.net.http.HttpTimeoutException: request timed out
        at jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:63) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1270) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:899) ~[java.net.http:?]

```

**Comment by scholzj** [comment] 2023-11-02 23:26
@Elyytscha I do not see anything suggesting it is the same issue. Your error suggests that there are issues communicating with your API server. That can be anything from your cluster issues, networking issues etc.

**Comment by Elyytscha** [comment] 2023-11-03 10:40
well, operator does not create pods in strimzipodset, so its basically the same error, maybe not the same cause,

fact is it is gke, so there can't be no network/cluster issues, google would have fixed this already.
the only change was done, was in operator, because update mode is set to automatic in our env

**Comment by scholzj** [comment] 2023-11-03 23:15
> fact is it is gke, so there can't be no network/cluster issues, google would have fixed this already.
the only change was done, was in operator, because update mode is set to automatic in our env

Right. But Strimzi _cannot have any bugs because I would have fixed them already_. Seriously, every service can fail (even Google's!) and every software can have bugs (even one I contribute to 😉). All I can say is that the error suggests Strimzi has some issues talking with the API server. As I said, it can be caused by a variety of things -> issues with networking, issues with the API server, misbehaving admission controllers etc. The last one can be even something that Google does not manage in your cluster and it caused issues in the past. But it does not seem to reproduce generally, so I cannot help much more.

**Comment by bmanuel1974** [comment] 2023-11-05 22:34
I have not been able to pull more logs, but we have been restarting the pod many times a day (4-5).  I'm not sure if we are running at some large scale, so I will share what i know:
- 42 Kafka resources installed
- 82 KafkaConnects
- 317 KafkaConnectors
- 2716 Kafka topics (only listing these for context)

Are there any additional metrics from the cluster that might help diagnose other than logs?   I will attempt to collect full logs as soon as possible.

**Comment by scholzj** [comment] 2023-11-05 23:54
That is a large scale. But it does not seem to correspond to the log as this is what I counted there:

> It is less then 10 minutes long but has over 4300 events when the Kafka resource was modified. This seemed to have happened over 4331 unique custom resources.

That is factor 100 higher. So I guess that would be something to look into as it seemed to me like that led to the operator making _a lot of Kubernetes API calls_ and the Kubernetes API server trying to manage it by not accepting the requests. Please see the attached test file with all the Kafka clusters from the log you shared previously (the format is `namespace/custom-resource-name` basically). Maybe those resources should not be there and that is what is causing your problem? The UUID-style namespace name might suggest they are the result of some tests or something that uses a random namespace?

[cluster-list.txt](https://github.com/strimzi/strimzi-kafka-operator/files/13261192/cluster-list.txt)

**Comment by bmanuel1974** [comment] 2023-11-06 00:34
The uuid style namespaces was just me sanitizing the actual namespace names.  Those are not the actual names.

**Comment by scholzj** [comment] 2023-11-06 00:55
Ok. But if you sanitized it correctly, that still leaves a huge number of resources regardless of the actual namespace names. If you sanitized it incorrectly and replaced the same namespace with multiple different UUIDs, then the log is useless (and you made me waste a lot of time analyzing it 😞).

**Comment by scholzj** [comment] 2023-11-30 16:22
Discussed on the community call on 30.11.2023: No update for a long time, so we are going to close it. If you are able to reproduce it and provide a log that is properly sanitized, feel free to reopen it. Thanks.

**Closed by scholzj** 2023-11-30 16:22 UTC
Labels: bug, needs-triage
