### ISSUE TITLE
[Bug]: generateCertificatesSecret will exceed Secret max size

### ISSUE THREAD

**Issue by dcais** [strimzi/strimzi-kafka-operator#10020] opened 2024-04-24 09:47 UTC
### Bug Description

when replica size over 160. generateCertificatesSecret will exceed Secret max size. 

### Steps to reproduce

1. change kafka replica size to 160
2. waiting

### Strimzi version

0.32.0

### Kubernetes version

1.18

### Installation method

yaml

### Infrastructure

Base-metal

### Configuration files and logs

Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.21.0.1/api/v1/namespaces/prd-kafka/secrets/hakutaku-kafka-kafka-brokers. Message: Secret "hakutaku-kafka-kafka-brokers" is invalid: data: Too long: must have at most 1048576 bytes. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=data, message=Too long: must have at most 1048576 bytes, reason=FieldValueTooLong, additionalProperties={})], group=null, kind=Secret, name=hakutaku-kafka-kafka-brokers, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Secret "hakutaku-kafka-kafka-brokers" is invalid: data: Too long: must have at most 1048576 bytes, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:709) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:689) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:640) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:576) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$retryWithExponentialBackoff$2(OperationSupport.java:618) ~[io.fabric8.kubernetes-client-6.2.0.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2079) ~[?:?]
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$4.onResponse(OkHttpClientImpl.java:277) ~[io.fabric8.kubernetes-httpclient-okhttp-6.2.0.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.12.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more

**Comment by scholzj** [comment] 2024-05-02 08:45
Triaged on the community call on 2.5.2024: Duplicate of #7687

**Closed by scholzj** 2024-05-02 08:45 UTC
Labels: bug, needs-triage
