### ISSUE TITLE
Dynamic SSL Configuration Update

### ISSUE THREAD

**Issue by somasundaram1996** [strimzi/strimzi-kafka-operator#7418] opened 2022-10-03 09:16 UTC
### Discussed in https://github.com/orgs/strimzi/discussions/7417

<div type='discussions-op-text'>

<sup>Originally posted by **somasundaram1996** October  3, 2022</sup>
Hi Is is possible to reload the truststore and keystore on broker side without rolling of the pods. Its creating downtime unnecessarily.

Is there a feature that I can use to update the keystores whenever the brokerCertChain is reloaded. </div>

**Comment by scholzj** [comment] 2022-10-03 09:24
Duplicate of #7417

**Closed by scholzj** 2022-10-03 09:24 UTC
