### ISSUE TITLE
Hashicorp Vault as a secret store

### ISSUE THREAD

**Issue by alpaca4j** [strimzi/strimzi-kafka-operator#5079] opened 2021-06-04 09:52 UTC
I'd like to see an integration with Vault as a certificate store instead of storing them as K8s Secrets. Most of our users use Vault as a central point of importing secrets to their workloads. This would be also great for integrating external clients, which cannot use secrets to inject credentials automatically, but instead can connect to Vault and get them from there.

In the KafkaUser CRD one could define vault as a storege option which could work instead/alongside with the standard Secret. Maybe a seperate CRD for storing connection information about Vault and only using an alias in the Kafkauser crd?

**Comment by scholzj** [comment] 2021-06-04 10:10
I wonder how much this is a duplicate of #929. But in general, wouldn't you want to store the secrets centrally all in one Vault instead of having a different Vault configured in every KafkaUser resource? Also, storing the certs elsewhere is complicated since there is no CRL support and I'm not sure how reliable would be the deletion of the certificates from Vault.

In any case, contributions are always welcomed - but we might need to start with a proposal here first since it is rather a big change (https://github.com/strimzi/proposals).

**Comment by scholzj** [comment] 2021-06-04 10:11
PS: You can also look at this with regards to reading the secrets from clients who cannot mount the secrets: https://github.com/strimzi/kafka-kubernetes-config-provider

**Comment by alpaca4j** [comment] 2021-06-04 10:19
Just to be clear, definitely I'd like to store them in a single Vault, I was thinking of a use case where there could be multiple Vaults and maybe other integrations in the future. #929 I think relates more to reusing a PKI located in Vault. I was thinking more about KafkaUser certs. I'll start with the proposal then, I did something similar in the past and might be able to help on this.

**Comment by scholzj** [comment] 2021-06-04 10:24
> Just to be clear, definitely I'd like to store them in a single Vault, I was thinking of a use case where there could be multiple Vaults and maybe other integrations in the future.

I think there are two things to consider ...
* How easy / hard it will be to do ad-hoc authentication / authorization to Vault - is it easy? Does it need to be bootstrapped at startup?
* How do we expect the workflows to work? Do we really want the KafkaUser author to define where the secret should be created? Without the CRL, I would say it might be more a responsibility for the administrator of the Kafka cluster.

> I think relates more to reusing a PKI located in Vault.

That is probably true. But there is demand for that as well. So we should make sure your proposal does not collide with such feature in the future (it of course does not have to implement it or propose it).

**Closed** 2022-04-12 15:01 UTC
Labels: enhancement
