### ISSUE TITLE
[Bug]: KafkaRebalance not respecting replicationThrottle

### ISSUE THREAD

**Issue by AlbertoEAF** [strimzi/strimzi-kafka-operator#10122] opened 2024-05-16 17:11 UTC
### Bug Description

Hello,

I was triggering a KafkaRebalance in the mode `add-brokers` after adding one broker to have a cluster with 6 brokers.

I set a really low threshold of replicationThrottle=10 (which is apparently in bytes/s according to the source code), as reported by the description of the `KafkaRebalance` with k9s:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/3976753/3e1c56cf-fca1-44bf-92a7-7651a98642f0)

however, I am observing writes to the new broker at a rate of ~140MiB/s:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/3976753/9c684b11-4b3a-4487-a264-f61c896e775f)

### Steps to reproduce

This is the KafkaRebalance CRD I wrote and approved at first:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: rebalance-proposal
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  # We expect to have to transfer ~800GB. At a max rate of 10MB/s (the cluster is currently operating at ~20-30MB/s), this amounts to ~22h:
  replicationThrottle: 10 # max bytes/s. By default there is no limit.  
  mode: add-brokers
  brokers: [5]  # Add 6th broker (index 5) to the cluster.
```

I first started with `replicationThrottle=10000` (supposedly ~10MB/s), but no throttling happened, so I tried 10 and the same write throughput to the new broker of 140MiB/s happened -- that's when I understood the parameter wasn't taking effect at all.

### Expected behavior

The `replicationThrottle` parameter should be respected, meaning my new broker would write at most `<replicationThrottle value> [bytes/s]`.

### Strimzi version

0.40.0

### Kubernetes version

kuberenetes v1.26.15-eks-adc7111

### Installation method

unknown but I can ask if needed

### Infrastructure

Amazon EKS

**Comment by scholzj** [comment] 2024-05-16 17:24
Is it a duplicate of https://github.com/strimzi/strimzi-kafka-operator/issues/9972?

**Comment by AlbertoEAF** [comment] 2024-05-16 17:33
Not sure, 

But I was just now reading the [docs on the `KafkaTopic`](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#follower-replication-throttled-replicas) and indeed the default values (which I'm using) for the topics in:
- [follower.replication.throttled.replicas](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#follower-replication-throttled-replicas)
- [leader.replication.throttled.replicas](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#leader-replication-throttled-replicas)

are to have no throttled replicas.

Does this mean I was simply misusing the system and I should set both these parameters in all my topics to "*" to benefit from this `replicationThrottle`?

Or it should be working already and this is not the solution?

**Comment by scholzj** [comment] 2024-05-16 17:37
I'm not sure what exactly you mean with setting them to `"*"`. But yes, configuring the throtling in the KafkaTopic resource might help.

**Comment by AlbertoEAF** [comment] 2024-05-16 17:38
> I'm not sure what exactly you mean with setting them to `"*"`. But yes, configuring the throtling in the KafkaTopic resource might help.

In the docs they state this:

> **follower.replication.throttled.replicas**
A list of replicas for which log replication should be throttled on the follower side. The list should describe a set of replicas in the form [PartitionId]:[BrokerId],[PartitionId]:[BrokerId]:… or alternatively the wildcard ‘*’ can be used to throttle all replicas for this topic.

Shouldn't I simply set `"*"` on those 2 parameters on all my topics to fix this?

**Comment by scholzj** [comment] 2024-05-16 17:42
Ahh, ok ... I'm afraid I do not know how it works in detail, sorry.

**Comment by fvaleri** [comment] 2024-05-17 09:27
@AlbertoEAF the issue is caused by the Topic Operator which reverts these throttling topic configs that are not part of the topic spec. They are updated dynamically by Cruise Control while the rebalance is running. See #9972 for more details and a possible workaround.

Cruise Control uses single partitions when setting these configs and updates them as needed according to the current traffic (workload model). Having a static configuration with * could make the rebalance less efficient, but it may help with reducing the impact on clients. Not sure how this would work in practice. Let us know your findings.

We are already working on a proper solution where the Topic Operator will automatically ignore both `leader.replication.throttled.replicas` and `follower.replication.throttled.replicas` when Cruise Control integration is enabled.

**Comment by ppatierno** [comment] 2024-05-30 08:24
Triaged on 30/5/2024: @AlbertoEAF we are going to close this one as duplicated of #9972 and @fvaleri is going to ping the community user interested to fix it. If not he will take care of it.

**Closed by ppatierno** 2024-05-30 08:24 UTC
Labels: bug, needs-triage
