### ISSUE TITLE
[Bug]: Kafka upgrade issue 2.8.0 -> 3.0.0 (zookeeper failures)

### ISSUE THREAD

**Issue by edgarkz** [strimzi/strimzi-kafka-operator#9527] opened 2024-01-09 09:11 UTC
### Bug Description

Hello,
We are running into zookeeper issues while upgrading kafka using the operator from 2.8.0 -> 3.0.0 
Our setup includes 3 zookeepers and 3 kafka brokers with below config (trimmed)

While upgrading the kafka version to 3.0.0:
 1) stimzi operator detects zookeper vesion upgrade is required and starts rolling restarts,
  1 zookeeper instance was upgraded fine,
  2 zookeeper instance starts and eventually throws the below log and keeps restarting:

```
2024-01-07 07:48:40,934 INFO Using org.apache.zookeeper.server.watch.WatchManager as watch manager (org.apache.zookeeper.server.watch.WatchManagerFactory) [main]
2024-01-07 07:48:40,934 INFO Using org.apache.zookeeper.server.watch.WatchManager as watch manager (org.apache.zookeeper.server.watch.WatchManagerFactory) [main]
2024-01-07 07:48:40,936 INFO zookeeper.snapshotSizeFactor = 0.33 (org.apache.zookeeper.server.ZKDatabase) [main]
2024-01-07 07:48:40,936 INFO zookeeper.commitLogCount=500 (org.apache.zookeeper.server.ZKDatabase) [main]
2024-01-07 07:48:41,233 INFO Using TLS encrypted quorum communication (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,233 INFO Port unification disabled (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,233 INFO multiAddress.enabled set to false (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,234 INFO multiAddress.reachabilityCheckEnabled set to true (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,234 INFO multiAddress.reachabilityCheckTimeoutMs set to 1000 (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,234 INFO QuorumPeer communication is not secured! (SASL auth disabled) (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,234 INFO quorum.cnxn.threads.size set to 20 (org.apache.zookeeper.server.quorum.QuorumPeer) [main]
2024-01-07 07:48:41,235 INFO Reading snapshot /var/lib/zookeeper/data/version-2/snapshot.600026f9b (org.apache.zookeeper.server.persistence.FileSnap) [main]
2024-01-07 07:48:42,535 WARN Got EOF exception while reading the digest, likely due to the reading an older snapshot. (org.apache.zookeeper.server.DataTree) [main]
```
Eventually after some restarts all 3 zookeeper instances enter unhealthy state and keep restarting

Can you please advise how to proceed from here?

**Zookeeper data directory1:**
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/68842306/b1f440a3-c468-4ebb-a72f-d97c314e5406)
2#
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/68842306/ed7eceb4-e4e0-4d55-904c-754087adad9e)
3#
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/68842306/d2cfe13b-a229-47e1-ac45-de19248f4022)

**Strimzi operator version:** 0.27.1
K8s EKS 1.24

### Steps to reproduce

Install 2.8.0 kafka using crd 
Upgrade crd to kafka 3.0.0

### Strimzi version

0.27.1

### Kubernetes version

EKS 1.24

### Installation method

Helm

### Infrastructure

Amazon EKS

### Configuration files and logs

``` 
  kafka:
    version: 2.8.0
    replicas: 3
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 200m
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
 config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
      auto.create.topics.enable: "false"
      message.max.bytes: 5242880
```

**Comment by scholzj** [comment] 2024-01-09 09:34
I guess this is duplicate of #9517?

**Closed** 2024-01-09 09:56 UTC
Labels: bug, needs-triage
