### ISSUE TITLE
Minimize empty patch API calls

### ISSUE THREAD

**Issue by nikkelma** [strimzi/strimzi-kafka-operator#4669] opened 2021-03-29 16:57 UTC
**Is your feature request related to a problem? Please describe.**

Rancher management server appears to listen on all Service patch requests, and could have increased overhead applied to it with a large number of Kafka installations in the same cluster. Some patches to Services appear empty and cause Rancher to churn on its own reconciliation as a result.

**Describe the solution you'd like**

Perform diffing or caching when reconciling resources around the Kafka installation to minimize API calls made to the k8s server.

**Describe alternatives you've considered**

Rancher is investigating if any alternatives exist to listening for all API calls surrounding Services to power its functionality around these objects.

**Additional context**

The combination of these two issues (Strimzi patching Services every reconciliation loop + Rancher reconciling its data on every Service patch) is the only apparent cause of degraded behavior. Although either fix will provide some relief, the ideal is to have both fixes implemented to guarantee minimal overhead in both contexts.

**Comment by scholzj** [comment] 2021-03-29 20:26
Thanks for raising this. I will have a look at it.

**Comment by wpwoodjr** [comment] 2021-04-08 14:59
We would like to see this resolved, we have 20-30 Strimzi clusters under management by Rancher and the overhead puts the environment at risk.

**Comment by scholzj** [comment] 2021-04-19 21:28
I opened a PR to fix this. I do not have/use any Rancher cluster. So I was unable to reproduce this issue there / or test the fix. After it is merged (or even while it is opened), it would be great if you can give it a try to confirm that it addressed the issue.

**Closed** 2021-04-27 15:56 UTC
Labels: enhancement
