### ISSUE TITLE
Upgrade strimzi operator 0.19.0=>0.20.1 caused wiping of all kafka clusters

### ISSUE THREAD

**Issue by vutkin** [strimzi/strimzi-kafka-operator#4882] opened 2021-05-03 10:54 UTC
**Describe the bug**
Upgrade strimzi operator 0.19.0=>0.20.1 caused wiping of all kafka clusters

**To Reproduce**
- helm chart failed to upgrade => delete CRD somehow => delete related CRD resources
- helm restored previous release including CRDs (but no resources)
- operator cleaned workload because no resources were found
- _PROFIT_ - Restored from latest backup using velero

**Expected behavior**
kafka clusters do rollout

**Environment (please complete the following information):**
 - Strimzi version: [0.19.0]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [v1.20.5]
 - Infrastructure: [Azure/AKS]

**YAML files and logs**
`helm upgrade --install strimzi strimzi/strimzi-kafka-operator --atomic --wait --timeout 1800s --namespace strimzi --values strimzi/values.yml --version 0.20.1 --set 'watchNamespaces={test-cluster}'`

W0430 12:25:14.979534     252 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

**Additional context**
Clusters and strimzi operator was moved to new cluster using velero tool.

**Comment by vutkin** [comment] 2021-05-03 10:59
https://github.com/strimzi/strimzi-kafka-operator/discussions/4748

**Comment by scholzj** [comment] 2021-05-03 11:03
Probably duplicate of #3877?

**Comment by vutkin** [comment] 2021-05-03 11:09
Hi @scholzj , looks like. Strange that missed it.

**Closed** 2021-05-06 08:30 UTC
Labels: bug, question
