### ISSUE TITLE
[Bug]: tls-side car container is missing in entity operator after kafka operator update from 0.37.0 to 0.39.0

### ISSUE THREAD

**Issue by flawless4g** [strimzi/strimzi-kafka-operator#9613] opened 2024-01-29 16:43 UTC
### Bug Description

Cluster/kafka operator (0.39.0) dependend entity deployment/pod doesn't contain tls sidecar, even if I directly declare in kafka itself resource configuration for entity pod tls sidecar container.

### Steps to reproduce

Update kafka-operator to 0.39.0 and kafka version to 3.6.1

### Expected behavior

0.39.0 kafka operator docs declare support of tls sidecar in entity operator (as well as topic-operator and user-operator that exist in entity operator pod for kafka 3.6.1)
So no alert on missing tls sidecar container is expected to appear

### Strimzi version

0.39.0

### Kubernetes version

3.6.1

### Installation method

helm chart

### Infrastructure

Amazon EKS

**Comment by scholzj** [comment] 2024-01-29 16:54
Duplicate of https://github.com/strimzi/strimzi-kafka-operator/issues/9597. Also, this is by design.

**Closed by scholzj** 2024-01-29 16:54 UTC
Labels: bug, needs-triage
