### ISSUE TITLE
io.vertx.core.VertxException: Thread blocked Exception

### ISSUE THREAD

**Issue by prakashshp92** [strimzi/strimzi-kafka-operator#4964] opened 2021-05-14 05:04 UTC
Hi,

I have a strimzi cluster with 2 kafka replicas and 1 zk replica. I'm using strimzi v0.19.0. 
I get the following exception from the strimzi cluster operator.

```
io.vertx.core.VertxException: Thread blocked
at java.lang.Object.wait (Native Method)
at java.lang.Object.wait (Object.java:328)
at org.apache.zookeeper.ClientCnxn.submitRequest (ClientCnxn.java:1529)
at org.apache.zookeeper.ClientCnxn.submitRequest (ClientCnxn.java:1512)
at org.apache.zookeeper.ClientCnxn.close (ClientCnxn.java:1481)
at org.apache.zookeeper.ZooKeeper.close (ZooKeeper.java:1415)
at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.closeConnection (ZookeeperScaler.java:245)
at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$scale$1 (ZookeeperScaler.java:99)


	at app//io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at app//io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at app//io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at app//io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at app//io.vertx.core.impl.FailedFuture.onComplete(FailedFuture.java:49)
	at app//io.vertx.core.Future.lambda$compose$3(Future.java:382)
	at app//io.vertx.core.Future$$Lambda$189/0x0000000840294840.handle(Unknown Source)
	at app//io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at app//io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at app//io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at app//io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$200/0x0000000840291c40.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at app//io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at app//io.vertx.core.impl.EventLoopContext$$Lambda$201/0x0000000840318040.run(Unknown Source)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
```

Can you please tell me how to fix this ?

**Comment by scholzj** [comment] 2021-05-14 08:14
I guess you can check if your ZooKeeper works properly. If it does, there is probably no fix for this.

**Comment by ppatierno** [comment] 2021-05-14 09:05
I was wondering if this problem should have been mitigated with https://github.com/strimzi/strimzi-kafka-operator/pull/4894 and https://github.com/strimzi/strimzi-kafka-operator/pull/4890 that anyway are in the latest 0.23.0 release.

**Comment by prakashshp92** [comment] 2021-05-14 10:19
@scholzj  Zookeeper pod is in running state. Can you tell me why this exception arises and how to fix it ?

**Comment by scholzj** [comment] 2021-05-14 10:32
As mentioned by Paolo - it is probably addressed by #4894 - at least that changed this part of code. I don't know what is to fix on it. Is it one of exception? Do the reconciliations continue afterwards? It is hard to say when all you shared is an exception.

**Comment by prakashshp92** [comment] 2021-05-14 10:40
I had a doubt whether this exception might have effect on the stability of the Kafka cluster. That's why I created an issue here.

**Comment by scholzj** [comment] 2021-05-14 11:56
As I said, that is hard to say without the full logs. If it happened once I do not think you need to be worried.

**Comment by MikeEdgar** [comment] 2021-05-14 13:38
I think this issue can be considered a duplicate of #4939

**Closed** 2021-10-31 22:07 UTC
Labels: question
