### ISSUE TITLE
Kafka PODs are not appearing, only zookeeper pods are running.

### ISSUE THREAD

**Issue by basavarajdhanashetti** [strimzi/strimzi-kafka-operator#3155] opened 2020-06-04 17:08 UTC
Hi,

I am using Strimzi 0.18.0 version. After following installation steps, I notice that only Zookeeper pods are runnings. I don't see any PODs related to Kafka. Can anyone help on this?

Here is my config yaml file contents: As part of this, I am expecting 3 Zookeeper PODS and 3 Kafka PODs runnings.
    
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: staffing-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2G
        deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1G
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}

When I query PODS, sts and services, I don't see Kafka pods.

> kubectl get all -n kafka

NAME                                            READY   STATUS    RESTARTS   AGE
pod/strimzi-cluster-operator-7c6bbfd894-lsmh6   1/1     Running   0          14m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/strimzi-cluster-operator   1/1     1            1           14m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/strimzi-cluster-operator-7c6bbfd894   1         1         1       14m

>  kubectl  get all -n kafka-cluster

NAME                               READY   STATUS    RESTARTS   AGE
pod/staffing-cluster-zookeeper-0   2/2     Running   0          12m
pod/staffing-cluster-zookeeper-1   2/2     Running   0          12m
pod/staffing-cluster-zookeeper-2   2/2     Running   0          12m

NAME                                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/staffing-cluster-zookeeper-client   ClusterIP   10.51.245.214   <none>        2181/TCP                     12m
service/staffing-cluster-zookeeper-nodes    ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   12m

NAME                                          READY   AGE
statefulset.apps/staffing-cluster-zookeeper   3/3     12m

**Comment by scholzj** [comment] 2020-06-04 18:41
You will probably need to share the logs form Zookeeper pods and from the cluster operator in order for us to be able to help you.

**Comment by olivegak971** [comment] 2020-07-01 08:31
Hi

I have the same behaviour with Strimzi 0.18, on a RKE cluster with Kubernetes 1.18.
Here are the cluster-operator logs when deploying strimzi-cluster-operator-0.18.0.yaml (after setting of right namespace): 
<<
INFO  ClusterOperator:87 - Creating ClusterOperator for namespace datalake-poc
2020-07-01 08:10:10 INFO  ClusterOperator:105 - Starting ClusterOperator for namespace datalake-poc
2020-07-01 08:10:10 INFO  ClusterOperator:119 - Opened watch for Kafka operator
2020-07-01 08:10:10 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker operator
2020-07-01 08:10:10 INFO  ClusterOperator:119 - Opened watch for KafkaConnect operator
2020-07-01 08:10:10 INFO  ClusterOperator:119 - Opened watch for KafkaBridge operator
2020-07-01 08:10:10 INFO  ClusterOperator:119 - Opened watch for KafkaMirrorMaker2 operator
2020-07-01 08:10:11 INFO  ClusterOperator:130 - Setting up periodic reconciliation for namespace datalake-poc
2020-07-01 08:10:11 INFO  ClusterOperator:192 - ClusterOperator is now ready (health server listening on 8080)
2020-07-01 08:10:11 INFO  Main:159 - Cluster Operator verticle started in namespace datalake-poc
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnects' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormaker2s' with unstable version 'v1alpha1'
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1alpha1'
2020-07-01 08:12:11 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkarebalances' with unstable version 'v1alpha1'
2020-07-01 08:14:11 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:16:11 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
.............
>>
Then i deploy a kafka + zookeeper (file included)
[broker.yml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4856582/broker.yml.txt)
and here are the logs : 
<<
INFO  OperatorWatcher:40 - Reconciliation #0(watch) Kafka(datalake-poc/broker): Kafka broker in namespace datalake-poc was ADDED
2020-07-01 08:19:48 INFO  AbstractOperator:173 - Reconciliation #0(watch) Kafka(datalake-poc/broker): Kafka broker should be created or updated
2020-07-01 08:19:48 INFO  OperatorWatcher:40 - Reconciliation #1(watch) Kafka(datalake-poc/broker): Kafka broker in namespace datalake-poc was MODIFIED
2020-07-01 08:19:58 WARN  AbstractOperator:247 - Reconciliation #1(watch) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:20:11 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:20:21 WARN  AbstractOperator:247 - Reconciliation #2(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:22:11 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:22:21 WARN  AbstractOperator:247 - Reconciliation #3(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:24:11 INFO  ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:24:21 WARN  AbstractOperator:247 - Reconciliation #4(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
.....  **and so on**
>>
I have a pod "broker-zookeeper-0" running and no pod for kafka
I mention that persistent volumes are well created and one of them is bound for zookeeper needs..

Thanks in advance

**Comment by scholzj** [comment] 2020-07-01 10:57
Actually, the log you copied misses the important point abouit how `Reconciliation #0(watch)` ends - can you share the full log? In general, you should try:
* `kubectl describe statefulset broker-kafka` and `kubectl get sts broker-kafka -o yaml`
(You can use https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh to collect all the logs and information automatically)

**Comment by olivegak971** [comment] 2020-07-02 08:41
Hi scholzj

Here is the zip generated by the report script.
[report-02-07-2020_10-26-18.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4862906/report-02-07-2020_10-26-18.zip)

I Tried to downgrade Kubernetes with 1.16 version but no change. I also tried Strimzi 0.17, no change, so I redeployed the 0.18 version. When I do a "kubectl describe kafka", i see the following error : 
<<
_Status:
  Conditions:
    Last Transition Time:  2020-07-02T07:59:27+0000
    Message:               Failed to connect to Zookeeper broker-zookeeper-0.broker-zookeeper-nodes.datalake-poc.svc:2181. Connection was not ready in 600000 ms.
    Reason:                ZookeeperScalingException
    Status:                True
    Type:                  NotReady
  Observed Generation:     1_
>>
Yet, the broker-zookeeper pod starts successfullly as well as both services : 
_broker-zookeeper-client   ClusterIP   10.43.11.1   <none>        2181/TCP                     45m
broker-zookeeper-nodes    ClusterIP   None         <none>        2181/TCP,2888/TCP,3888/TCP   45m_

Moreover, I have only one sts, broker-zookeeper, so I guess the cluster operator doesn't even deploy the sts corresponding to kafka. 
Your help will be precious because I just don't know what to do now.

Regards

**Comment by scholzj** [comment] 2020-07-02 20:35
For what ever reason, the report tooldidn't collected the pods and logs from Zookeeper. Can you check if they are ready and if yes, download and share their logs?

**Comment by olivegak971** [comment] 2020-07-03 08:22
I finally found the cause. It was firewalld which blocked any requests to coredns. 
For now, I stopped it but i would like to restart it with the right iptables rules. 
Did you hear about such issues ?

In any case, thanks for your help

**Comment by ssharma2089** [comment] 2020-07-08 15:48
I am facing the similar issue. Please find the attachment for the zookeeper logs.

[zookeeper-logs-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4891704/zookeeper-logs-0.txt)

**Comment by scholzj** [comment] 2020-07-08 18:34
@ssharma2089 I think you will need to describe more about your issue. What versions are you using, is it a new cluster etc. Some of the errors are about hostname verification - so this might help: https://github.com/strimzi/strimzi-kafka-operator/issues/3099#issuecomment-636480754 ... but without more context and reproducing it I'm pretty much just guessing.

**Comment by scholzj** [comment] 2020-07-29 12:37
Did this helped? Can we close the issue?

**Comment by discordiaZA** [comment] 2020-08-17 17:45
@scholzj I am having a similar issue when upgrading from 0.17 to either 0.18 or 0.19. Would it be possible to describe a sequence of steps to follow to document the state of the clusters for debugging purposes?

**Comment by scholzj** [comment] 2020-08-17 18:55
As described above, you can do the following:
* Check the status section of the Kafka resource
* Get the logs form all Zookeeper pods and Cluster Operator pod
* Get the StatefulSet YAMLs

Most of that should be done by the report tool we have: https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh

**Comment by donovanmuller** [comment] 2020-08-17 20:46
I've also hit this issue with `0.19` on a `1.15.11` RKE cluster.
I updated the cluster operator from `0.14` and am getting the following in the Zookeeper logs on startup:

```
...
2020-08-17 20:09:35,502 INFO Started @913ms (org.eclipse.jetty.server.Server) [main]
2020-08-17 20:09:35,502 INFO Started AdminServer on address 0.0.0.0, port 8080 and command URL /commands (org.apache.zookeeper.server.admin.JettyAdminServer) [main]
2020-08-17 20:09:35,506 INFO Election port bind maximum retries is 3 (org.apache.zookeeper.server.quorum.QuorumCnxManager) [main]
2020-08-17 20:09:35,509 INFO Creating TLS-only quorum server socket (org.apache.zookeeper.server.quorum.QuorumCnxManager) [QuorumPeerListener]
2020-08-17 20:09:35,512 WARN Failed to resolve address: test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeerListener]
java.net.UnknownHostException: test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:197)
	at org.apache.zookeeper.server.quorum.QuorumPeer.recreateSocketAddresses(QuorumPeer.java:746)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:914)
2020-08-17 20:09:35,513 WARN Failed to resolve address: test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeerListener]
java.net.UnknownHostException: test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1248)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:197)
	at org.apache.zookeeper.server.quorum.QuorumPeer.recreateSocketAddresses(QuorumPeer.java:756)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:914)
2020-08-17 20:09:35,513 INFO My election bind port: test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc:3888 (org.apache.zookeeper.server.quorum.QuorumCnxManager) [QuorumPeerListener]
2020-08-17 20:09:35,514 ERROR Exception while listening (org.apache.zookeeper.server.quorum.QuorumCnxManager) [test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc:3888]
java.net.SocketException: Unresolved address
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:388)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:349)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:919)
2020-08-17 20:09:35,519 INFO LOOKING (org.apache.zookeeper.server.quorum.QuorumPeer) [QuorumPeer[myid=1](plain=127.0.0.1:12181)
...

2020-08-17 20:15:09,570 ERROR Failed to verify hostname: worker-1.test.com(org.apache.zookeeper.common.ZKTrustManager) [test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc/10.42.7.211:3888]
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <worker-1.test.com> doesn't match any of the subject alternative names: [*.test-kafka-zookeeper-client.test-shared.svc, *.test-kafka-zookeeper-client.test-shared.svc.cluster.local, test-kafka-zookeeper-2.test-kafka-zookeeper-nodes.test-shared.svc.cluster.local, test-kafka-zookeeper-2.test-kafka-zookeeper-nodes.test-shared.svc, *.test-kafka-zookeeper-nodes.test-shared.svc, test-kafka-zookeeper-client.test-shared.svc, test-kafka-zookeeper-client.test-shared.svc.cluster.local, test-kafka-zookeeper-client, test-kafka-zookeeper-client.test-shared, *.test-kafka-zookeeper-nodes.test-shared.svc.cluster.local]
	at org.apache.zookeeper.common.ZKHostnameVerifier.matchDNSName(ZKHostnameVerifier.java:224)

2020-08-17 20:15:09,547 INFO Received connection request 192.240.36.128:40006 (org.apache.zookeeper.server.quorum.QuorumCnxManager) [test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc/10.42.7.211:3888]
2020-08-17 20:15:09,569 ERROR Failed to verify host address: 192.240.36.128 (org.apache.zookeeper.common.ZKTrustManager) [test-kafka-zookeeper-0.test-kafka-zookeeper-nodes.test-shared.svc/10.42.7.211:3888]
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.240.36.128> doesn't match any of the subject alternative names: [*.test-kafka-zookeeper-client.test-shared.svc, *.test-kafka-zookeeper-client.test-shared.svc.cluster.local, test-kafka-zookeeper-2.test-kafka-zookeeper-nodes.test-shared.svc.cluster.local, test-kafka-zookeeper-2.test-kafka-zookeeper-nodes.test-shared.svc, *.test-kafka-zookeeper-nodes.test-shared.svc, test-kafka-zookeeper-client.test-shared.svc, test-kafka-zookeeper-client.test-shared.svc.cluster.local, test-kafka-zookeeper-client, test-kafka-zookeeper-client.test-shared, *.test-kafka-zookeeper-nodes.test-shared.svc.cluster.local]
...
```

What's weird is it's resolving the node (`worker-1.test.com`) hostname and node IP (`192.240.36.128`) when comparing the certificate SANs:

```
Certificate for <worker-1.test.com> doesn't match any of the subject alternative names...
Certificate for <192.240.36.128> doesn't match any of the subject alternative names...
```

The workaround suggested in https://github.com/strimzi/strimzi-kafka-operator/issues/3099#issuecomment-636480754 does result in the Kafka still StatefulSet coming up:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: test-kafka
spec:
...
  zookeeper:
    replicas: 3
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
...
```

I have two clusters, both `1.15.11` RKE clusters. This cluster fails with the errors above, however, the other cluster which has never had Strimzi operators installed, did _not_ have this issue. Configurations and resources were identical.

**Comment by scholzj** [comment] 2020-08-17 20:55
@donovanmuller So in your case it seems to be fairly clear ... you seem to have some strange DNS configuration there is the pod resolves to worker node name and node IP. I never used RKE, so I have no idea how does it normally work. Glad at least the work around helped in your case.

**Comment by scholzj** [comment] 2020-08-26 21:25
Is there actually still anything to answer or help with? Or can we close this?

**Closed** 2020-09-19 21:00 UTC
Labels: question

**Comment by networkingana** [comment] 2021-07-18 13:11
I have the same issue on 0.24.0 
this is the report generated from the report.sh script
[report-18-07-2021_09-05-45.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6836295/report-18-07-2021_09-05-45.zip)

**Comment by scholzj** [comment] 2021-07-18 14:09
@networkingana How does that relate to https://github.com/strimzi/strimzi-kafka-operator/discussions/5316? Because there the storage seems to be the issue.

**Comment by minhtuyenvp02** [comment] 2024-04-07 08:05
> Hi,
> 
> I am using Strimzi 0.18.0 version. After following installation steps, I notice that only Zookeeper pods are runnings. I don't see any PODs related to Kafka. Can anyone help on this?
> 
> Here is my config yaml file contents: As part of this, I am expecting 3 Zookeeper PODS and 3 Kafka PODs runnings.
> 
> apiVersion: kafka.strimzi.io/v1beta1 kind: Kafka metadata: name: staffing-cluster spec: kafka: version: 2.5.0 replicas: 3 listeners: plain: {} tls: {} config: offsets.topic.replication.factor: 2 transaction.state.log.replication.factor: 2 transaction.state.log.min.isr: 2 log.message.format.version: "2.5" storage: type: jbod volumes: - id: 0 type: persistent-claim size: 2G deleteClaim: true zookeeper: replicas: 3 storage: type: persistent-claim size: 1G deleteClaim: true entityOperator: topicOperator: {} userOperator: {}
> 
> When I query PODS, sts and services, I don't see Kafka pods.
> 
> > kubectl get all -n kafka
> 
> NAME READY STATUS RESTARTS AGE pod/strimzi-cluster-operator-7c6bbfd894-lsmh6 1/1 Running 0 14m
> 
> NAME READY UP-TO-DATE AVAILABLE AGE deployment.apps/strimzi-cluster-operator 1/1 1 1 14m
> 
> NAME DESIRED CURRENT READY AGE replicaset.apps/strimzi-cluster-operator-7c6bbfd894 1 1 1 14m
> 
> > kubectl  get all -n kafka-cluster
> 
> NAME READY STATUS RESTARTS AGE pod/staffing-cluster-zookeeper-0 2/2 Running 0 12m pod/staffing-cluster-zookeeper-1 2/2 Running 0 12m pod/staffing-cluster-zookeeper-2 2/2 Running 0 12m
> 
> NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE service/staffing-cluster-zookeeper-client ClusterIP 10.51.245.214 2181/TCP 12m service/staffing-cluster-zookeeper-nodes ClusterIP None 2181/TCP,2888/TCP,3888/TCP 12m
> 
> NAME READY AGE statefulset.apps/staffing-cluster-zookeeper 3/3 12m
 I have the same issue. Did you fix it?
