### ISSUE TITLE
How to support the authentication using SASL/PLAIN?

### ISSUE THREAD

**Issue by EresZX** [strimzi/strimzi-kafka-operator#2221] opened 2019-11-20 07:27 UTC
I modify the source code of kafka-operator to support the authentication using SASL/PLAIN,but I meet some problems.
Firstly, I remove the restriction of the related configuration options in KafkaSpecCluster.java,including:

``
listeners, security.inter.broker.protocol, sasl.mechanism.inter.broker.protocol, 
sasl.enabled.mechanisms, listener.name.sasl_plaintext.plain.sasl.jaas.config, sasl.jaas.config.
``

Then, I use the operator generated by the modify version.
When I deploy the kafka cluster,I add the following config in the yaml file.

config:
``      
offsets.topic.replication.factor: 1
``
``
transaction.state.log.replication.factor: 1
`` 
``
     transaction.state.log.min.isr: 1
`` 
``
     log.message.format.version: "2.3"
``
`` 
     listeners: SASL_SSL://localhost:9092
``
``
      security.inter.broker.protocol: SASL_SSL
``
`` 
     sasl.enabled.mechanisms: PLAIN
  ``
``
    sasl.mechanism.inter.broker.protocol: PLAIN
  ``
``
 sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret" user_alice="alice-secret";
``

The kafka container can't be created rightly, the error in the log of kafka container is:

``
2019-11-20 06:58:10,472 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main]
java.lang.IllegalArgumentException: Error creating broker listeners from 'SASL_SSL://localhost:9092': No security protocol defined for listener SASL_SSL
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:314)
	at kafka.server.KafkaConfig.$anonfun$listeners$1(KafkaConfig.scala:1384)
	at scala.Option.map(Option.scala:163)
	at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:1383)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1483)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:68)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener SASL_SSL
	at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:48)
	at scala.collection.immutable.Map$Map3.getOrElse(Map.scala:181)
	at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:48)
	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:56)
	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:311)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:39)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:311)
	... 10 more
``

I don't know how to solve this problem.Is this my configuration information is wrong or the operator itself does not support SASL/PLAIN authentication mechanism?

**Comment by scholzj** [comment] 2019-11-20 16:52
We do not support SASL/PLAIN. The reason is that it would be fairly lot of effort to manage the users in a secure way and the SASL PLAIN it self is not completely secure (plaintext passwords sent over the network etc.).

I'm not sure what exactly have you modified. But just changing the cluster operator will not be enough since some of these configurations will be overridden in the docker image / will conflict with the values set there. So you would need modify both.

**Comment by EresZX** [comment] 2019-11-21 02:17
I find the conflict values in the script kafka_config_generator.sh in the docker images/. Do you mean I need to modify them by reading the value from my customize configuration. Otherwise, my customize configuration will be overridden in this script.

**Comment by scholzj** [comment] 2019-11-21 21:56
Yes, you will need to modify and rebuild all the containers as well.

**Comment by scholzj** [comment] 2019-11-21 21:56
Out of curiosity - why do you want / need to use SASL PLAIN instead of SASL SCRAM which we support?

**Comment by EresZX** [comment] 2019-11-22 08:56
We use both of SASL PLAIN and SASL SCRAM. Because of some business needs,we need to modify the support of  SASL PLAIN.

**Comment by EresZX** [comment] 2019-11-22 09:26
I want to add the value sasl_plain to the api listener.plain.authentication.type. Then, I could tell the operator that I want to use SASL PLAIN and modify the conflict values in the script kafka_config_generator.sh in the docker images/.

I add KafkaListenerAuthenticationSASL.java in api/…/model/listener.
[KafkaListenerAuthenticationSASL.java.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3878746/KafkaListenerAuthenticationSASL.java.txt)

I also modify the  KafkaListenerAuthentication.java to support subType of listener as following:
``
@JsonSubTypes({
        @JsonSubTypes.Type(name = KafkaListenerAuthenticationTls.TYPE_TLS, value = KafkaListenerAuthenticationTls.class),
        @JsonSubTypes.Type(name = KafkaListenerAuthenticationScramSha512.SCRAM_SHA_512, value = KafkaListenerAuthenticationScramSha512.class),
        @JsonSubTypes.Type(name = KafkaListenerAuthenticationOAuth.TYPE_OAUTH, value = KafkaListenerAuthenticationOAuth.class),
        @JsonSubTypes.Type(name = KafkaListenerAuthenticationSASL.SASL_PLAIN, value = KafkaListenerAuthenticationSASL.class),
})
``
[KafkaListenerAuthentication.java.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3878767/KafkaListenerAuthentication.java.txt)

However,when I use the following yaml file to deploy the kafka cluster, it seems not to work and the yaml file contains invalid value sasl_plain.
``
spec:
``
  ``
  kafka:
  ``
``
    version: 2.3.0
``
``
  replicas: 1
``
``
    listeners:
``
``
      plain:
 ``
``
      authentication:
 ``
``
         type: sasl_plain
  ``
``
    tls: {}
``

The error is:
``
The Kafka "my-cluster" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"kafka.strimzi.io/v1beta1", "kind":"Kafka", "metadata":map[string]interface {}{"creationTimestamp":"2019-11-22T08:46:02Z", "generation":1, "name":"my-cluster", "namespace":"kafka", "uid":"a0bc72da-add6-4b99-8b69-1b5e4012a1e3"}, "spec":map[string]interface {}{"entityOperator":map[string]interface {}{"topicOperator":map[string]interface {}{}, "userOperator":map[string]interface {}{}}, "kafka":map[string]interface {}{"config":map[string]interface {}{"listener.name.client.plain.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\" user_admin=\"admin-secret\" user_alice=\"alice-secret\"", "log.message.format.version":"2.3", "offsets.topic.replication.factor":1, "transaction.state.log.min.isr":1, "transaction.state.log.replication.factor":1, "zookeeper.connect":"zk-headless1:2181"}, "listeners":map[string]interface {}{"plain":map[string]interface {}{"authentication":map[string]interface {}{"type":"sasl_plain"}}, "tls":map[string]interface {}{}}, "replicas":1, "storage":map[string]interface {}{"class":"local-disks", "deleteClaim":true, "size":"100Gi", "type":"persistent-claim"}, "version":"2.3.0"}, "zookeeper":map[string]interface {}{"replicas":1, "storage":map[string]interface {}{"class":"local-disks", "deleteClaim":true, "size":"100Gi", "type":"persistent-claim"}}}}: validation failure list:
spec.kafka.listeners.plain.authentication.type in body should be one of [tls scram-sha-512 oauth]
`` 

How can I solve this problem and add the value sasl_plain to the api listener.plain.authentication.type.

**Comment by scholzj** [comment] 2019-11-25 08:40
Have you rebuilt the whole project? I think in general what you described should work.

**Comment by EresZX** [comment] 2019-11-25 09:01
I think I find the problem, the kafka image has not been updated. I still use the original kafka image.

**Comment by scholzj** [comment] 2020-04-05 22:39
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.

**Closed by scholzj** 2020-04-05 22:39 UTC
Labels: question

**Comment by abhi1git** [comment] 2021-06-07 15:13
@scholzj Just wanted to know two things 
* Whether SASL_PLAIN auth mechanism was released in any strimzi version after your latest comment on this thread ?
* If not is SASL_PLAIN auth mechanism planned in any future release ?

**Comment by scholzj** [comment] 2021-06-07 15:41
Strimzi does not support SASL PLAIN mechanism. The only exception is that you can use OAuth over SASL PLAIN - that that is only if you use `type: oauth` authentication.

**Comment by RafalSkolasinski** [comment] 2023-06-09 00:53
is this still the case? docs seems to mention SASL PLAIN [here](https://strimzi.io/docs/operators/0.35.0/configuring.html#type-KafkaClientAuthenticationPlain-reference) but the configuration seems to be rejected by the operator 

```
The Kafka "default" is invalid: spec.kafka.listeners[1].authentication.type: Unsupported value: "plain": supported values: "tls", "scram-sha-512", "oauth", "custom"
```

**Comment by scholzj** [comment] 2023-06-09 08:12
SALP/PLAIN is not supported on the broker side. It is supported only in the client based operands such as KAfkaCOnnect etc.

**Comment by alexey-demyanov** [comment] 2023-08-10 14:59
Hey! Here's solution:

```yaml
listeners:
- authentication:
    listenerConfig:
      org.apache.kafka.common.security.plain.PlainLoginModule: required
      plain.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule
        required username="admin" password="admins" user_alice="qwerty123"
        user_bob="16dc33e5b674306e"\;
      sasl.enabled.mechanisms: PLAIN
    sasl: true
    type: custom
  name: saslplain
  port: 9094
```

**Comment by archupsg03** [comment] 2023-09-27 17:42
the above plain config is not working. Ca you help ?

[2023-09-27 17:39:41,739] WARN [Producer clientId=console-producer] Error connecting to node my-cluster-kafka-bootstrap.authsionprem.svc:9092 (id: -1 rack: null) (org.apache.kafka.clients.NetworkClient)
java.io.IOException: Channel could not be created for socket java.nio.channels.SocketChannel[closed]
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:348)
        at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:329)
        at org.apache.kafka.common.network.Selector.connect(Selector.java:256)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:992)
        at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
        at org.apache.kafka.clients.NetworkClientUtils.isReady(NetworkClientUtils.java:42)
        at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:64)
        at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:534)
        at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:455)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
        at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:239)
        at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:338)
        ... 14 more
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to create SaslClient with mechanism SCRAM-SHA-256
