### ISSUE TITLE
Kafka Pod never appear

### ISSUE THREAD

**Issue by olivegak971** [strimzi/strimzi-kafka-operator#3266] opened 2020-07-01 08:37 UTC
Hi

I have a strangesame behaviour with Strimzi 0.18, on a RKE cluster with Kubernetes 1.18.
When I deploy my "broker.yml" definition, zookeeper pod are created but not kafka pod. 
[broker.yml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4856662/broker.yml.txt)

Here are the cluster-operator logs when deploying strimzi-cluster-operator-0.18.0.yaml (after setting of right namespace):
<<
INFO ClusterOperator:87 - Creating ClusterOperator for namespace datalake-poc
2020-07-01 08:10:10 INFO ClusterOperator:105 - Starting ClusterOperator for namespace datalake-poc
2020-07-01 08:10:10 INFO ClusterOperator:119 - Opened watch for Kafka operator
2020-07-01 08:10:10 INFO ClusterOperator:119 - Opened watch for KafkaMirrorMaker operator
2020-07-01 08:10:10 INFO ClusterOperator:119 - Opened watch for KafkaConnect operator
2020-07-01 08:10:10 INFO ClusterOperator:119 - Opened watch for KafkaBridge operator
2020-07-01 08:10:10 INFO ClusterOperator:119 - Opened watch for KafkaMirrorMaker2 operator
2020-07-01 08:10:11 INFO ClusterOperator:130 - Setting up periodic reconciliation for namespace datalake-poc
2020-07-01 08:10:11 INFO ClusterOperator:192 - ClusterOperator is now ready (health server listening on 8080)
2020-07-01 08:10:11 INFO Main:159 - Cluster Operator verticle started in namespace datalake-poc
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkaconnects' with unstable version 'v1beta1'
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkamirrormaker2s' with unstable version 'v1alpha1'
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1alpha1'
2020-07-01 08:12:11 WARN VersionUsageUtils:60 - The client is using resource type 'kafkarebalances' with unstable version 'v1alpha1'
2020-07-01 08:14:11 INFO ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:16:11 INFO ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
.............

Then i deploy a kafka + zookeeper. 
here are the logs :
<<
INFO OperatorWatcher:40 - Reconciliation #0(watch) Kafka(datalake-poc/broker): Kafka broker in namespace datalake-poc was ADDED
2020-07-01 08:19:48 INFO AbstractOperator:173 - Reconciliation #0(watch) Kafka(datalake-poc/broker): Kafka broker should be created or updated
2020-07-01 08:19:48 INFO OperatorWatcher:40 - Reconciliation #1(watch) Kafka(datalake-poc/broker): Kafka broker in namespace datalake-poc was MODIFIED
2020-07-01 08:19:58 WARN AbstractOperator:247 - Reconciliation #1(watch) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:20:11 INFO ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:20:21 WARN AbstractOperator:247 - Reconciliation #2(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:22:11 INFO ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:22:21 WARN AbstractOperator:247 - Reconciliation #3(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
2020-07-01 08:24:11 INFO ClusterOperator:132 - Triggering periodic reconciliation for namespace datalake-poc...
2020-07-01 08:24:21 WARN AbstractOperator:247 - Reconciliation #4(timer) Kafka(datalake-poc/broker): Failed to acquire lock lock::datalake-poc::Kafka::broker within 10000ms.
..... and so on

I have a pod "broker-zookeeper-0" running and no pod for kafka
I mention that persistent volumes are well created and one of them is bound for zookeeper needs..

Thanks in advance

**Comment by stanlyDoge** [comment] 2020-07-02 10:08
Could you please provide output of these commands?
```
oc get sts -n datalake-poc
oc get events -n datalake-poc
```

**Comment by scholzj** [comment] 2020-07-02 20:40
Is this duplicate to #3155?

**Comment by olivegak971** [comment] 2020-07-03 08:20
Yes it the same problem. 
Anyway i have resolved it. It was firewalld which blocked any requests to coredns. 
For now, I stopped it but i would like to restart it with the right iptables rules. 
Did you hear about such issues ?

In any case, thanks for your help

**Comment by scholzj** [comment] 2020-07-03 19:57
I don't think I heard about aby firewall issues with CoreDNS.

**Comment by scholzj** [comment] 2020-08-26 21:29
Is there still something we can help with here? Or can we close the issue? Thanks

**Comment by yaariyuval** [comment] 2020-09-13 11:55
Please do not close the issue; I'm experiencing it as well (Strimzi 0.19).
I had Istio annotations to disable the sidecar injections, but wanted to remove it and use Istio.
I updated the CR, it updated ZooKeeper (I believe that just fine), but stopped there and didn't update the Kafka STS.

**Comment by scholzj** [comment] 2020-09-13 12:05
I do not think Strimzi will work with the Istio sidecars etc. You will need to configure Istio to leave Strimzi be.

**Comment by yaariyuval** [comment] 2020-09-13 13:58
Thanks @scholzj, I reached the same conclusion.

**Comment by scholzj** [comment] 2020-09-19 20:50
@yaariyuval So, do you think we can close this now? Or do you still want to keep this open?

**Comment by yaariyuval** [comment] 2020-09-20 04:58
@scholzj I'd definitely not look for reasons to close bugs, but ways to fix them.
The original issue doesn't mention Istio, and regardless, the error message should be way clearer.

**Comment by scholzj** [comment] 2020-09-20 11:41
This is not a bug. This is  question which was answered and solved. The original author did not commented on it since more than 2 months and since you also do not seem to have anything more, it is correct to close this question.

**Closed by scholzj** 2020-09-20 11:41 UTC
Labels: question
