### ISSUE TITLE
Topic and User Operators can currently watch only a single namespace

### ISSUE THREAD

**Issue by Tombar** [strimzi/strimzi-kafka-operator#879] opened 2018-09-20 20:46 UTC
Moving our slack talk into an issue, for more context (https://strimzi.slack.com/archives/CBNKX522Z/p1537231193000100)

@scholzj:
> The topic and user operators can currently watch only a single namespace ... the main reason is that it is quite complicated to deal with the namespacing in Kafka. Such as _What to do when topic `my-topic` exists in 5 different namespaces and each of them has a different configuration_. (edited)
> 
> Since Kafka doesn't natively support any namespacing, we need to first come up with way how to _inject_ the namespace concept into Kafka. Then the operators can work accross more namespaces
> 

The problem I see with this is, strimzi operator can watch over multiple NS and create KafkaClusters or KafkaConnect in them, this is great :slightly_smiling_face:  but when trying to use this combined with authZ & authN in this scenario all secrets are created in the kafkaCluster NS and there is a need to manually copy/sync them to the right NS

I think having the user operator watch more than one namespace is more useful/important than the topic operator for most people to begin with, since for example, anyone that wants to split kafka and kafka connect into 2 namespaces would need to use it.

again, @scholzj mentioned a couple options:

> It is probably easier to address this for the users. But I'm not sure whether its desired to have this inconsistency when one part can do it and other not. Also expecially when using SASL SCRAM-SHA we can have only one password. So the problem is still what to do with users in multiple namespaces.
> 
> I wonder if having a field in the KafkaUser to specify the namespace where the secret should be created is better solution
> @tombentley @ppatierno Could you think about this? Any reason why the UO couldn't create the secrets in custom namespaces? As long as the user deploys the RBAC correctly?

Happy to test or brainstorm solutions

**Comment by denniseffing** [comment] 2020-03-17 10:02
Is there any word on the current situation? We also noticed that secrets are created in the Kafka cluster namespace and that we need to manually copy/sync them to the correct namespace, which is why we ultimately landed here.

**Comment by scholzj** [comment] 2022-02-22 15:30
Triaged on 22.02.2022: This is still desired and often asked for -> we should keep it.

**Comment by scholzj** [comment] 2022-02-23 20:09
Duplicate of #5895 #6301 -> closing this issue and keeping the other issues since they are separate the TO and UO problematic and solution is not the same.

**Closed by scholzj** 2022-02-23 20:09 UTC
Labels: enhancement, topic operator, needs-proposal
