### ISSUE TITLE
[One of the Kafka Cluster re-created/re-deployed abnormally..Need Help] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3577] opened 2020-09-01 10:23 UTC
Hi Team,

We are working on a use case that has a single namespace with multiple Kafka clusters inside. After launching the clusters over a period of time we have observed that one of the Kafka clusters got re-created and all its related secrets got changed which impacted the certs. 

We would like to understand what exactly has caused this behavior as it is very frequently observed. I am attaching the strimzi operator logs, Kafka CR, and also the entity operator logs for tls-sidecar and user-operator.

[entity-operator_tls-sidecar.log](https://github.com/strimzi/strimzi-kafka-operator/files/5155564/entity-operator_tls-sidecar.log)
[entity-operator_user-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/5155565/entity-operator_user-operator.log)

[strimzi-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5155570/strimzi-operator.txt)
[sedsep-dev-kafka-cluster-command.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5155585/sedsep-dev-kafka-cluster-command.txt)

Please let us know if you require any Kafka/zookeeper logs to check this.

**Comment by scholzj** [comment] 2020-09-01 19:18
I think there was a similar issue opened by someone recently. But I guess you can start by explaining what _recreated_ means and which components were impacted. Regenerated secrets are very different from everything was deleted.

**Comment by scholzj** [comment] 2020-09-01 19:19
It would be also good to know what Strimzi version you use.

**Comment by jrivers96** [comment] 2020-09-02 18:34
I had the similar issue and I have `*` turned on for the cluster operator, but only have a single kafka cluster.

**Comment by jrivers96** [comment] 2020-09-03 12:03
Saw this again this morning on a production cluster: 
```
k get secrets
kafka-cluster-clients-ca                            Opaque                                1      4h45m
kafka-cluster-clients-ca-cert                       Opaque                                3      4h45m
kafka-cluster-cluster-ca                            Opaque                                1      4h45m
kafka-cluster-cluster-ca-cert                       Opaque                                3      4h45m
kafka-cluster-cluster-operator-certs                Opaque                                4      4h45m
kafka-cluster-entity-operator-certs                 Opaque                                4      4h41m
kafka-cluster-entity-operator-token-q8nmz           kubernetes.io/service-account-token   3      4h41m
kafka-cluster-kafka-brokers                         Opaque                                68     4h43m
kafka-cluster-kafka-exporter-certs                  Opaque                                4      4h41m
kafka-cluster-kafka-exporter-token-gkl86            kubernetes.io/service-account-token   3      4h41m
kafka-cluster-kafka-token-cbn8s                     kubernetes.io/service-account-token   3      4h44m
kafka-cluster-zookeeper-nodes                       Opaque                                12     4h45m
kafka-cluster-zookeeper-token-f4br9                 kubernetes.io/service-account-token   3      4h45m
```

```
k -n namespace get svc
NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)                               AGE
kafka-cluster-kafka-0                    LoadBalancer   10.100.242.21    .us-east-1.amazonaws.com   9094:32188/TCP                        4h45m
kafka-cluster-kafka-1                    LoadBalancer   10.100.148.151  .elb.us-east-1.amazonaws.com   9094:31523/TCP                        4h45m
kafka-cluster-kafka-10                   LoadBalancer   10.100.24.200    .elb.us-east-1.amazonaws.com   9094:31263/TCP                        4h45m
kafka-cluster-kafka-11                   LoadBalancer   10.100.14.219    .elb.us-east-1.amazonaws.com   9094:31473/TCP                        4h45m
kafka-cluster-kafka-12                   LoadBalancer   10.100.255.112   .elb.us-east-1.amazonaws.com   9094:32486/TCP                        4h45m
kafka-cluster-kafka-13                   LoadBalancer   10.100.68.98     .elb.us-east-1.amazonaws.com   9094:30322/TCP                        4h45m
kafka-cluster-kafka-14                   LoadBalancer   10.100.209.248   .elb.us-east-1.amazonaws.com   9094:31910/TCP                        4h45m
kafka-cluster-kafka-15                   LoadBalancer   10.100.178.203   .elb.us-east-1.amazonaws.com   9094:32573/TCP                        4h45m
kafka-cluster-kafka-16                   LoadBalancer   10.100.47.86     .elb.us-east-1.amazonaws.com   9094:31510/TCP                        4h45m
kafka-cluster-kafka-2                    LoadBalancer   10.100.222.52   .elb.us-east-1.amazonaws.com   9094:32624/TCP                        4h45m
kafka-cluster-kafka-3                    LoadBalancer   10.100.90.147    .elb.us-east-1.amazonaws.com   9094:30028/TCP                        4h45m
kafka-cluster-kafka-4                    LoadBalancer   10.100.101.88    .elb.us-east-1.amazonaws.com   9094:30967/TCP                        4h45m
kafka-cluster-kafka-5                    LoadBalancer   10.100.46.21     .elb.us-east-1.amazonaws.com   9094:30412/TCP                        4h45m
kafka-cluster-kafka-6                    LoadBalancer   10.100.57.242    .elb.us-east-1.amazonaws.com   9094:30901/TCP                        4h45m
kafka-cluster-kafka-7                    LoadBalancer   10.100.4.223     .elb.us-east-1.amazonaws.com   9094:30310/TCP                        4h45m
kafka-cluster-kafka-8                    LoadBalancer   10.100.178.88    .elb.us-east-1.amazonaws.com   9094:30394/TCP                        4h45m
kafka-cluster-kafka-9                    LoadBalancer   10.100.219.215   .elb.us-east-1.amazonaws.com   9094:31744/TCP                        4h45m
```

**Comment by scholzj** [comment] 2020-09-03 15:00
@jrivers96 any chance you have the DEBUG logs from the cluster operator?

**Comment by jrivers96** [comment] 2020-09-03 15:07
No, I don't. I'll turn them on for our dev and production cluster though if it happens again. 

I'm thinking about turning off the "watch all namespaces" feature. Do you think this is superstitious or a good idea?

**Comment by jrivers96** [comment] 2020-09-03 15:15
Also, what would your procedure be to recover from something like this? 

The cluster is currently writing data, but could zookeeper/brokers be in a bad state? I intend to restart a few of the brokers and see if they come back during cluster down time. If they do not, then I'll have to wipe out the broker and zookeeper volumes?

**Comment by scholzj** [comment] 2020-09-03 23:35
> I'm thinking about turning off the "watch all namespaces" feature and just have it watch a single namespace. Do you think this is a good idea?

I do not see any relation there. But then, I do not see why would this happen at all so who knows :-(.

> Also, what would your procedure be to recover from something like this?

I don't know. You should not use the `deleteClaim: true` in the storage configuration. That should normally keep the volumes ok and the cluster should be able to continue from them. Some user also opened a PR to make it configurable if the owner reference is set for the CA secrets. But that would help only if I assume right and it is Kubernetes Garbage Collection deleting the resources.

For the rolling update, you can also use this annotation: https://strimzi.io/docs/operators/latest/full/using.html#proc-manual-rolling-update-kafka-deployment-configuration-kafka ... but that triggers it for the full stateful set and not just one pod.

**Comment by fcantournet** [comment] 2020-10-19 16:28
I think we've seen something very similar happen in production yesterday around 15h20 CEST.

The kafka & zookeeper sts as well as most ressources were deleted & then recreated later on.

Looking at the logs they were deleted by the kubernetes garbage collector : `system:serviceaccount:kube-system:generic-garbage-collector`

I don't know what's going on but the `kafka` CR that owns these STS was not deleted.
It still shows with a creation date much older :

```apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  annotations:
    helm.fluxcd.io/antecedent: platform:helmrelease/platform-kafka
  creationTimestamp: "2020-06-22T19:31:08Z"
  generation: 17
  labels:
    app: platform-kafka
  name: platform-kafka
  namespace: platform
```

**Comment by scholzj** [comment] 2020-10-19 16:33
The STS are owned by the Kafka CR. So if GC deleted them it probably thought it was deleted?

**Comment by fcantournet** [comment] 2020-10-19 16:45
I don't know what mecanism would cause that to happen.
I'll try to check if I have access to the GC logs but it's unlikely since we run on GKE.

NB: Our strimzi operator was being killed by OOM every 2 hours or so, we just fixed that, but the timing do not seem to coincide at all

**Comment by vperi1730** [comment] 2020-11-11 06:33
@scholzj  - I would like to bring the same question back with a simple observation with one of my Kafka cluster deployed in GCP. 

Today morning I have noticed out of my 3 replicas Kafka nodes 2 of them got re-created/re-started which shows a diff age for all the 3 nodes. Something like below, 19h is the correct time when i have launched initially.

```
pod/cluster17-kafka-0                           2/2     Running   0          5h46m
pod/cluster17-kafka-1                           2/2     Running   0          19h
pod/cluster17-kafka-2                           2/2     Running   0          12h
```

However, the cluster ca certs which I have used yesterday to produce and consume messages on a topic still holds valid as i am able to achieve it. 

So the question is why there is a restart of the Kafka nodes in this case, thoughts?

**Comment by scholzj** [comment] 2020-11-11 09:11
That cannot be answered so easily ... it could be anything from the pod exiting, Kube killing it etc. If the Strimzi Operator had anything to do with it, it would be in the logs. But in most caes the operator would roll all of the pods around the same time.

**Comment by jrivers96** [comment] 2020-12-08 19:15
We just had this happen three times since 12/6/2020 on two different clusters after running okay for a few months. One is a production cluster which doesn't really change. We took measures to give cluster operator a lot more resource 8GB now. We are looking at upgrading EKS from 1.15. 

I'll check to see if we have any interesting logs.

**Comment by scholzj** [comment] 2020-12-08 19:26
So, do you think it took so long to reproduce because it was building to the OOM with more memory? Also, just to refresh my memory ... did Java killed it self because of OOM? Or did Kube killed it because of OOM?

**Comment by jrivers96** [comment] 2020-12-08 19:30
I think it took longer to reproduce, because it OOMs less with more memory. I think Kube kills it. I'm not sure at the moment how to know that. If you `kubectl describe pod`, the last state is listed as `killed`

**Comment by jrivers96** [comment] 2020-12-08 21:03
I'm reading through these two issues: 

https://github.com/fabric8io/kubernetes-client/issues/2135

https://github.com/fabric8io/kubernetes-client/pull/1800

I'm still getting a lot of these in the cluster operator logs: 
```io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 130891115 (154997701)```

**Comment by jrivers96** [comment] 2020-12-08 21:46
Unfortunately, I didn't have DEBUG logs on. I set the following which didn't seem to do anything. How do you turn on cluster-operator logs? 

```           
 - name: STRIMZI_LOG_LEVEL
              value: "DEBUG"```

This is kind of interesting. https://opensource.com/article/20/6/kubernetes-garbage-collection

I'm still trying to understand it. I have the cluster-operator set to watch `*` namespaces.

**Comment by scholzj** [comment] 2020-12-08 22:10
> This is kind of interesting. https://opensource.com/article/20/6/kubernetes-garbage-collection

I know they do not work cross namespace. It is one of the obstacles for making the User Operator create secrets in different namespaces. Strimzi should not create and cross namespace owner references since we do not create anything across namespaces. Everything belonging to single custom resources ends up in the same namespace. So I do not think the owner reference should trigger this.

> I think it took longer to reproduce, because it OOMs less with more memory. I think Kube kills it. I'm not sure at the moment how to know that. If you kubectl describe pod, the last state is listed as killed

That should mean Kubernetes killed it. `reason: OOM Killed` basically means the pod tried to get more memory than what the request / limit is. In theory, `JAVA_OPTS` env var might be used to control the -Xmx and similar options to configure against that. Not sure how that helps.

> I'm still getting a lot of these in the cluster operator logs:
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 130891115 (154997701)

My understanding ... when you setup a watch in Kubernetes, you tell it to give you the events from version X. As new resources are created, the version is increasing and at some point there might have been so many changes that the version you started with is too old and Kube cannot maintain the watch for it anymore. So they give you this error, you reconnect and start a new watch with the new version. So (assuming I'm right with my understanding) this is just based on the turnover of different events and resources in your Kube cluster and that is why it sometimes happens more often and sometimes less often.

> Unfortunately, I didn't have DEBUG logs on. I set the following which didn't seem to do anything. How do you turn on cluster-operator logs?

What version of Strimzi do you use? The `STRIMZI_LOG_LEVEL` should work in all up to 0.19. From 0.20, it is better to configure it in the ConfigMap instead of in the env var (but it should still work.)

**Comment by jrivers96** [comment] 2020-12-08 22:19
cluster operator logs are turned on successfully for DEV and PRO now. I didn't apply it before because it was stuck in our change control process.

**Comment by jrivers96** [comment] 2020-12-09 14:32
Any suggestions about potential experiments? 

I was thinking about instancing a small cluster and having a process kill the cluster operator over and over. I'll try to capture logs/stack dump. 

It seems the certificate changes and the cluster operator is built to detect that and re-spin everything?

**Comment by scholzj** [comment] 2020-12-09 17:21
I was actually a bit two quick yesterday when I said we use the owner references only for resources in the same namespace. Overnight I realised there are two cases where this is not true:
* The cluster role bindings create when rack awareness / node port listeners are being used
* The role bindings created when the UO and TO are configured to watch another namespace than they run in. 

I opened a PR to fix the first issue. Will look later at the second issue. I guess one of the questions is whether your cluster is using one of the features described above and whether they might be relevant for you or now.

**Comment by jrivers96** [comment] 2020-12-09 18:21
I have the cluster-operator set to watch * namespaces. There are connectors in those other namespaces.

**Comment by jrivers96** [comment] 2020-12-09 18:56
kafka:
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 15Gi
    template:
       pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - foo
    version: 2.5.0
    replicas: 35
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: https://REDACT/auth/realms/pro-realm/protocol/openid-connect/certs
          validIssuerUri: https://REDACT/auth/realms/pro-realm
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300
      external:
        type: loadbalancer
        configuration:
          brokerCertChainAndKey:
            secretName: external-cert-secret
            certificate: ca.crt
            key: ca.key
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: REDACT
          validIssuerUri: REDACT
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300
        overrides:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: REDACT
              external-dns.alpha.kubernetes.io/ttl: "60"
              address: REDACT
    rack:
      topologyKey: failure-domain.beta.kubernetes.io/zone

**Comment by scholzj** [comment] 2020-12-09 19:07
Watching multiple namespaces in the Cluster Operator is not a problem. But the Rack Awareness would definitely cause the ClusterRoleBinding with the owner reference to be created. I tried to reproduce it by restarting the master plane ... nothing happened in my case. But that could mean nothing of course.

**Comment by jrivers96** [comment] 2020-12-09 19:37
Any suggestions on how I might patch the system for now? Or do I have to wait until 0.21?

**Comment by scholzj** [comment] 2020-12-09 19:47
I'm afraid I do not have any workaround :-(. 0.21 will hopefully happen soon - although I thought it would be great to have also Kafka 2.7.0 there. We might also do 0.20.1 => if we do I will make sure this is included.

**Comment by jrivers96** [comment] 2020-12-09 20:07
The 0.20.1 would be greatly appreciated, critical system for us. Can chat about this on phone if interested. A number of our groups use strimzi.

**Comment by scholzj** [comment] 2020-12-11 15:23
I did today the https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.20.1-rc1 which includes both fixes. Feel free to test it if you want. As long as all testing goes fine, it might be released in few days.

**Comment by scholzj** [comment] 2020-12-15 14:04
So, the 0.20.1 is now released: https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.20.1 ... it includes both fixes to the ownerReferences. As I said before ... I'm a bit sceptical this is the issue. But feel free to give it a try and let me know if the problem appears again even after this fix and I can try to look further for another issues.

**Comment by jrivers96** [comment] 2020-12-15 20:34
We've installed this in our DEV environment. Thank you very much. 

I don't fully understand how and when this gets tripped. I'm still trying to understand how the owner references work.

**Comment by jrivers96** [comment] 2020-12-15 23:55
This issue is interesting. We copy the strimzi cluster certs to other namespaces...

https://github.com/elastic/cloud-on-k8s/issues/3986

**Comment by scholzj** [comment] 2020-12-15 23:58
I do not know how you copy them. But I assume you can copy them without the ownerReference, that should be just about implementing it in whatever tool you use.

**Comment by jrivers96** [comment] 2020-12-16 00:07
There are all sorts of race conditions when you violate the cross namespace rule too. 

https://github.com/kubernetes/kubernetes/pull/92743

**Comment by jrivers96** [comment] 2020-12-16 15:30
I downloaded this tool: https://github.com/kubernetes-sigs/kubectl-check-ownerreferences

I ran it on two different dev clusters. It shows the problem with strimzi in 0.20 and it shows the ownership problem as resolved in 0.21. 

It also shows me having problems with the secrets as I copy them around the cluster. 


```
kubectl-check-ownerreferences
GROUP   RESOURCE   NAMESPACE    NAME                            OWNER_UID                              LEVEL   MESSAGE
        secrets    FOO   kafka-cluster-cluster-ca-cert   77d4d452-da72-46b1-bbab-58eb22a8e22e   Error   child namespace does not match owner namespace (FOO-strimzi-dev)
rbac.authorization.k8s.io   clusterrolebindings                strimzi-FOO-strimzi-dev-kafka-cluster-kafka-init   77d4d452-da72-46b1-bbab-58eb22a8e22e   Error   cannot reference namespaced type as owner (apiVersion=kafka.strimzi.io/v1beta1,kind=Kafka)
2 errors, 0 warnings
```

```
kubectl-check-ownerreferences









GROUP   RESOURCE   NAMESPACE       NAME                            OWNER_UID                              LEVEL   MESSAGE
        secrets    FOO1       kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
        secrets    FOO2   kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
        secrets    FOO3   kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
        secrets    FOO4          kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
        secrets    FOO5             kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
        secrets    FOO6      kafka-cluster-cluster-ca-cert   f119d87f-d7b7-461b-8ed5-702b2c162c54   Error   child namespace does not match owner namespace (FOO-strimzi-pro)
```

**Comment by scholzj** [comment] 2021-02-17 23:31
@jrivers96 So ... with the owner references fixed ... do you still see the issue with the cluster being re-created?

**Closed** 2021-03-24 22:01 UTC
Labels: question

**Comment by jrivers96** [comment] 2022-04-11 13:54
No, we do not see the issue with the cluster being re-created anymore.
