### ISSUE TITLE
[Question] Why does the cluster operator think my cluster has been updated?

### ISSUE THREAD

**Issue by matthewpwilson** [strimzi/strimzi-kafka-operator#2691] opened 2020-03-12 11:17 UTC
The cluster operator seems to be detecting my cluster has been modified on each reconcile loop, and rolling the pods as a result.   This happens constantly, starting from a clean install of the operator and cluster CR.  I can't figure what it thinks has changed.
```
 INFO  OperatorWatcher:40 - Reconciliation #2(watch) Kafka(coffeeshop/my-cluster): Kafka my-cluster in namespace coffeeshop was MODIFIED
```

I'm also seeing few exceptions when updating resources:
```
es.client.KubernetesClientException: Failure executing: PATCH at: https://172.30.0.1/apis/apps/v1/namespaces/coffeeshop/deployments/my-cluster-entity-operator. Message: the server rejected our request due to an error in our request. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server rejected our request due to an error in our request, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:300) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:829) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:152) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:27) ~[io.fabric8.kubernetes-model-4.6.2.jar:4.6.2]
	at io.fabric8.kubernetes.api.model.apps.DoneableDeployment.done(DoneableDeployment.java:6) ~[io.fabric8.kubernetes-model-4.6.2.jar:4.6.2]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:158) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.patch(RollableScalableResourceOperation.java:167) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:113) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:45) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:111) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.patch(DeploymentOperationsImpl.java:45) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:167) ~[io.strimzi.operator-common-0.16.2.jar:0.16.2]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.internalPatch(DeploymentOperator.java:85) ~[io.strimzi.operator-common-0.16.2.jar:0.16.2]
	at io.strimzi.operator.common.operator.resource.DeploymentOperator.internalPatch(DeploymentOperator.java:22) ~[io.strimzi.operator-common-0.16.2.jar:0.16.2]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalPatch(AbstractResourceOperator.java:162) ~[io.strimzi.operator-common-0.16.2.jar:0.16.2]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:103) ~[io.strimzi.operator-common-0.16.2.jar:0.16.2]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-03-12 10:35:57 WARN  AbstractOperator:268 - Reconciliation #0(watch) Kafka(coffeeshop/my-cluster): Failed to reconcile
```

Strimzi version: 0.16.2
Installed method: YAML files or OperatorHub
Platform: OpenShift 4.3

**Comment by matthewpwilson** [comment] 2020-03-12 11:18
Log with DEBUG set:
[strimzi-cluster-operator-chopped.log](https://github.com/strimzi/strimzi-kafka-operator/files/4323822/strimzi-cluster-operator-chopped.log)

**Comment by scholzj** [comment] 2020-03-12 14:57
Thsi is weird. For whatever reason your cluster seems to be changing the images names in the pods:
```
2020-03-12 10:33:57 DEBUG StatefulSetDiff:98 - Current StatefulSet path /spec/template/spec/containers/1/image has value "docker.io/strimzi/kafka@sha256:66281e4e9f687b27a85c9ef2ecbb76909e4fa611717d627a14c4cfeb0a212825"
2020-03-12 10:33:57 DEBUG StatefulSetDiff:99 - Desired StatefulSet path /spec/template/spec/containers/1/image has value "strimzi/kafka:0.16.2-kafka-2.4.0"
```

I haven't seen this in OpenShift 4.3. Can you share the custom resource? Also, are you sure you have just one operator running which would be watching given namespace and managing given cluster?

There also seem to be some issues with the connection to the API server. SO I wonder if the operator has enough resources.

Can you share your Kafka CR? I can try to reproduce it exactly with that.

**Comment by matthewpwilson** [comment] 2020-03-12 16:33
OK I've found the problem.  In the log I gave you I did indeed have two operators watching the namespace, sorry about that. After resolving that I was able to spot the real issue - the log snippets you posted gave me the clue I needed
```
2020-03-12 10:33:13 DEBUG StatefulSetDiff:98 - Current StatefulSet path /metadata/annotations/kappnav.status.flyover.nls has value "\"status.flyover.unregistered\""
2020-03-12 10:33:13 DEBUG StatefulSetDiff:99 - Desired StatefulSet path /metadata/annotations/kappnav.status.flyover.nls has value 
```
This and a bunch of other annotations were being added by kappnav every time Strimzi recreated the resources - operator fight! Uninstalling kappnav made the problem go away. 

The question remains here - should Strimzi ignore annotations in its diff?

**Comment by scholzj** [comment] 2020-03-12 16:39
We do not ignore annotation changes as some annotations are relevant and should not be ignored. Are these some annotations added by you or by some tooling? I guess that if needed we can add them so some kind of whitelist to have them ignored.

**Comment by matthewpwilson** [comment] 2020-03-13 08:14
The annotations are being added by the kAppNav operator https://github.com/kappnav/README

**Comment by scholzj** [comment] 2020-03-13 09:18
Ok, I never used that. If you can collect the annotations it is adding, I can add them to some white/black list to be ignored.

**Comment by scholzj** [comment] 2020-04-05 22:34
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.

**Closed by scholzj** 2020-04-05 22:34 UTC
Labels: question
