### ISSUE TITLE
Certs Renewal Issue

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#6326] opened 2022-02-08 14:15 UTC
Hi Strimzi team,

We are observing an issue recently where the cluster-ca and client-ca certs expired for a product team using Strimzi kafka operator. Post expiration of the certificates, the team tried renewing them by using the "force-renew: true" annotation method, referring to the official 
[kafka_sacclusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024486/kafka_sacclusterlogs.txt)
[strimzi-operator-sacclusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024487/strimzi-operator-sacclusterlogs.txt)
[zookeeper_sac-clusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024488/zookeeper_sac-clusterlogs.txt)
documentation, (https://strimzi.io/docs/operators/in-development/configuring.html#proc-renewing-ca-certs-manually-str). We are under the impression that this activity should be performed before the expiration date, while the certificates are still valid - please help to clarify if this is not the case.

Post trying this, "force-renew: true" annotation method, the kafka, entity operator and kafka-exporter pods are in crash loop back-off. Also, there is an error message in the tls-sidecar container.
**"SSL_accept: 1408F10B: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number"**

The operator logs suggest that it is not able to establish a connection with zookeeper.

Please advise on how to recover the cluster in such a state.

Please find attached logs from kafka, zookeeper and operator. Please let me know if any other information is needed.

**Comment by saloni-2404** [comment] 2022-02-08 14:16
[kafka_sacclusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024507/kafka_sacclusterlogs.txt)
[strimzi-operator-sacclusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024508/strimzi-operator-sacclusterlogs.txt)
[zookeeper_sac-clusterlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8024509/zookeeper_sac-clusterlogs.txt)

**Comment by scholzj** [comment] 2022-02-08 14:17
Duplicate of #6321?

**Closed by scholzj** 2022-02-08 14:17 UTC
Labels: bug
