### ISSUE TITLE
Kafka Users are created with ACL entries and during performing operations allowed by ACL we see Denied Operation

### ISSUE THREAD

**Issue by Janardhan78** [strimzi/strimzi-kafka-operator#10103] opened 2024-05-14 09:51 UTC
### Discussed in https://github.com/orgs/strimzi/discussions/10102

<div type='discussions-op-text'>

<sup>Originally posted by **Janardhan78** May 14, 2024</sup>
We are using 0.36.1 version of strimzi and 3.5.1 version of kafka 

We have created 2 KafkaUsers from Strimzi operator for 2 different cluster with ACL entries. we have observed that the ACL entries in teh Kafka Cluster will not be present for approximately 4 minutes  and the ACL entries will be available after that. The clients which are using KafkaUser to perform operations not be able to perform operations till the ACL is available in KafkaCLuster.

We see in the Kafka Logs below are the mesages the user and cluster details in messages are not added since it is proprietery

Processing notification(s) to /config/change

Processing override for entityPath

Removing PRODUCE quota for user

Removing FETCH quota for user

Removing REQUEST quota for user

Removing CONTROLLER_MUTATION quota for user

Processing notification(s) to /kafka-acl-changes

Processing Acl change notification for

Processing notification(s) to /config/changes

Processing notification(s) to /kafka-acl-changes

Processing Acl change notification for ResourcePattern(resourceType=GROU

 

The same behavior is observed even if we create a single KafkaUser , same behavior is observed

 

 We tried to check by creating a ACL in Kafka Cluster we see that ACL is getting removed in kafkacluster. 

Even if we try to add a ACL manually from kafka cluster the same behavior is seen. After some time the ACL is getting deleted. Have raised a Bug in ASF https://issues.apache.org/jira/browse/KAFKA-16693. I havent received any response for the same. Has any one facing similar issue ?

 

kafka-acls --add --allow-host '*' --allow-principal User:'CN=jana-2' --operation Describe --resource-pattern-type LITERAL --topic my-new-topic --bootstrap-server eric-data-message-bus-kf-9-kafka-bootstrap:9091 -command-config /tmp/kafka_ssl_config.properties 
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Adding ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

 

ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:24:53 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:24:58 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:02 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:06 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:10 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:15 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:19 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:24 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:28 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:32 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:36 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:40 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:45 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:49 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:53 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:25:58 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:02 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:06 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:10 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:15 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:19 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:23 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:28 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:32 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Current ACLs for resource `ResourcePattern(resourceType=TOPIC, name=my-new-topic, patternType=LITERAL)`: 
     (principal=User:CN=jana-2, host=*, operation=DESCRIBE, permissionType=ALLOW) 

Mon May 13 14:26:36 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Mon May 13 14:26:40 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Mon May 13 14:26:45 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
^CMon May 13 14:26:48 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'
Mon May 13 14:26:52 UTC 2024
ERROR StatusLogger Reconfiguration failed: No configuration found for '2cdf8d8a' at 'null' in 'null'

</div>

**Comment by scholzj** [comment] 2024-05-14 12:54
Duplicate of #10102. Why do you open issue and discussion at the same time? It makes no sense and just creates span and wastes time of people.

**Closed by scholzj** 2024-05-14 12:54 UTC
