### ISSUE TITLE
How can I set specific host for advertised.listener with nodeport type?

### ISSUE THREAD

**Issue by arezvani** [strimzi/strimzi-kafka-operator#8133] opened 2023-02-20 15:11 UTC
Hi,
I want to have external access to my kafka cluster. I use nodeport type for listener but I didn't find any option that I can set my desired host. I have a load balancer for worker nodes that have a public IP and i set a host and domain for that for example ali.kafka.com.

What should I do? Please help me

**Comment by scholzj** [comment] 2023-02-20 20:36
Duplicate of #8132 ... why do you open it twice?

**Closed by scholzj** 2023-02-20 20:36 UTC
Labels: documentation
