### ISSUE TITLE
[Enhancement] Support Topic Configuration endpoint in Cruise Control/KafkaRebalance

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3267] opened 2020-07-01 10:14 UTC
**Is your feature request related to a problem? Please describe.**
Currently the KafkaRebalance operator does not support the topic configuration endpoint and so does not allow users to modify the topic replication factor.
https://github.com/linkedin/cruise-control/wiki/REST-APIs#change-kafka-topic-configuration
Brought up on slack here: https://cloud-native.slack.com/archives/CMH3Q3SNP/p1593597807298500

**Describe the solution you'd like**
CC operator should be able to use this endpoint and be configurable via the KafkaRebalance custom resource.
There may be complications surrounding the topic operator.

**Comment by tomncooper** [comment] 2020-07-01 10:29
We definitely should support the features of the CC topic config endpoint. This lets you alter the number replicas for a topic (which is a feature we have requests for quite a lot) and have them balanced across the cluster. 

The issue, as you say, is how this ties in with the TO. The TO and `KafakTopic` CR is the method Strimzi provides for interacting with topics, we probably shouldn't introduce a separate method (via a new CR) for changing just the topic replicas?

If we want to allow changing the replica count in the KafkaTopic CR, then the TO will need to know how to talk to CC or will need to be coupled into the KafkaRebalanceAssemblyOperator somehow. 

None of this is insurmountable, but we need to think through how everything will link together, as I don't think having a `KafkaTopicConfigChange` CR is a viable starting point (but others may disagree).

**Comment by samuel-hawker** [comment] 2020-07-01 10:33
If we change the number of replicas, would the bidirectional nature of the TO not mean that the KafkaTopic resource would be updates when the topic is updated?
Is there some other complication here?

**Comment by tomncooper** [comment] 2020-07-01 10:35
I think it would update. The issue is if we want to add another CR for doing that?

**Comment by scholzj** [comment] 2020-07-01 11:00
I think this needs to be done through KafkaTopic CRs - the solution needs to be IMHO done in the scope of #191 and not as a separate cruise control thing.

**Comment by ppatierno** [comment] 2020-07-01 12:00
Yes, I agree. It should be on the TO shoulders doing this. It's not strictly a rebalance related stuff so using a `KafkaRebalance` resource could not make sense to the user. Of course, we need to re-use the Cruise Control API client we have in the KafkaRebalanceAssemblyOperator. Maybe it should be moved in the operator-common, that could be the first step to do.

**Comment by samuel-hawker** [comment] 2020-07-01 13:36
Thanks for linking to that issue Jakub, I agree with Paolo here that re-using the CC API here might be really useful and potentially will solve the optimaization problem that Tom mentions here:
https://github.com/strimzi/strimzi-kafka-operator/issues/191#issuecomment-456853465

Should I close this issue in favour of #191 or perhaps re-purpose this one to something like the following?
**[ENHANCEMENT] Move Cruise Control API to operator-common**

**Comment by scholzj** [comment] 2022-03-31 14:19
Triaged on 31.3.2022: Let's keep #191 open and close this one.

**Closed by scholzj** 2022-03-31 14:19 UTC
Labels: enhancement
