### ISSUE TITLE
Optional Load Balancer (+ external IP) for bootstrap server when using type "loadbalancer"

### ISSUE THREAD

**Issue by trietsch** [strimzi/strimzi-kafka-operator#4433] opened 2021-02-17 10:45 UTC
**Is your feature request related to a problem? Please describe.**
When using type `loadbalancer` for a Kafka listener, `n+1` Load Balancers are created in Kubernetes, `n` for the amount of brokers and 1 for the bootstrap server.

**Describe the solution you'd like**
The bootstrap server is only for convenience (as discussed [here](https://github.com/strimzi/strimzi-kafka-operator/discussions/4430)), which may not be always necessary. Providing a flag in the configuration for the `loadbalancer` type listener stating whether to provision a Load Balancer for the bootstrap server would be a nice addition.

**Describe alternatives you've considered**
The only alternative now is to always provision a bootstrap Load Balancer service.

**Comment by Sh1n** [comment] 2021-03-01 11:01
I am also looking for a way to disable the +1 bootstrap server on a given listener.

**Comment by scholzj** [comment] 2021-03-02 23:44
FYI: I have this on my TODO list, but do not expect to get to it in 0.22 ... probably will have some time to look into it in 0.23.

**Comment by yyang48** [comment] 2021-12-10 23:54
Just checked, we have two bootstrap services in a single Kafka Cluster. For instance, in a running Kafka Cluster managed by strimzi in AWS EKS, we have the following k8s services created by strimzi: 
```test-kafka-01-cruise-control
 test-kafka-01-kafka-0
 test-kafka-01-kafka-1
 test-kafka-01-kafka-2
 test-kafka-01-kafka-3
 test-kafka-01-kafka-4
 test-kafka-01-kafka-5
 test-kafka-01-kafka-bootstrap
 test-kafka-01-kafka-brokers
 test-kafka-01-kafka-external-bootstrap
 test-kafka-01-zookeeper-client
 test-kafka-01-zookeeper-nodes
```

It seems like the strimzi will create one Load Balancer for the  `test-kafka-01-kafka-external-bootstrap` service, not the `test-kafka-01-kafka-bootstrap`. The `test-kafka-01-kafka-bootstrap` is used internally by the cruise control. 

So this issue is to give an option NOT to create the `test-kafka-01-kafka-external-bootstrap` service? With this, the Load Balancer for this service will not be created as well. There is no change for the ` test-kafka-01-kafka-bootstrap`

Is this correct?

**Comment by scholzj** [comment] 2021-12-11 00:23
I think the name will be a bit different depending on the listener name in the Kafka CR. But yes, the regular `test-kafka-01-kafka-bootstrap` service should be kept -> only the `test-kafka-01-kafka-external-bootstrap` would be basically not created if the user does not want to use it (the motivation is usually to save costs - the `test-kafka-01-kafka-external-bootstrap` is convenient for configuring the clients, but strictly speaking not needed).

**Comment by yyang48** [comment] 2021-12-14 06:23
I'm thinking to add a boolean properties `doNotCreateExternalBootstrapService` in the `GenericKafkaListenerConfigurationBootstrap` Schema. And set the default value as `false`.

For the listener type `internal`, this properties will be ignored, as we always create an internal bootstrap service.

For the other external listener types (`ingress`, `load Balancer`, `nodeport` and` route`), this properties will decide whether to create the External Bootstrap service for this Kafka Cluster, or not.

Does this sounds reasonable? Any other suggestions?

**Comment by scholzj** [comment] 2021-12-14 09:54
I think we need to think about it a bit - the name and to which it should apply. I think the issue is only with load balancers. Not really with Ingress, Routes or node ports. So maybe we should start with loadbalancers only. But to be able to extend it in the future give it a generic name ... maybe `bootstrapService` or `createBootstrapService` and have it default to true? Also, maybe it would be easier to have it directly in the configuration section and not in the bootstrap configuration?

@tombentley WDYT about the naming?

**Comment by yyang48** [comment] 2021-12-15 19:56
Got it, thanks for the explanation!

**Comment by yyang48** [comment] 2022-01-12 04:21
@scholzj please assign this issue to me, I opened a PR for this issue. thanks!

**Closed** 2022-01-24 19:03 UTC
Labels: enhancement, good-start
