### ISSUE TITLE
[Bug]: Grafana dashboard failed to found datasource

### ISSUE THREAD

**Issue by insider89** [strimzi/strimzi-kafka-operator#8582] opened 2023-05-29 15:41 UTC
### Bug Description

When you install latest strimzi helm chart with `dashboards.enabled: true`, Grafana won't found datasource for strimzi dashboards:
```
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found
```

Version of strimzi helm chart: 0.35
Grafan version: 9.5.2
<img width="1496" alt="Screenshot 2023-05-29 at 18 36 47" src="https://github.com/strimzi/strimzi-kafka-operator/assets/17744154/48ba04cd-2536-483b-aff0-1094e8bc6c70">

 

### Steps to reproduce

1. Install strimzi helm chart with the following value:
```
dashboards:
    enabled: true
```

### Expected behavior

Grafana dashboards found the datasource

### Strimzi version

0.35.0

### Kubernetes version

1.27.1

### Installation method

helm chart

### Infrastructure

Amazon EKS

### Additional context

Looks like related issue in Grafana GitHub:
https://github.com/grafana/grafana/issues/10786

If it doesn't work by default, I think we should remove add it through helm chart values. Better people modify Grafana json and add it themself.

**Comment by scholzj** [comment] 2023-05-29 15:42
Duplicate of #8545?

**Comment by scholzj** [comment] 2023-05-29 15:43
> If it doesn't work by default, I think we should remove add it through helm chart values. Better people modify Grafana json and add it themself.

I'm not sure what exactly are you suggesting here ... this seems to work for some people and not for others. SO it is not clear if it can be just _removed_.

**Comment by insider89** [comment] 2023-05-29 15:48
@scholzj Yes, duplicate. 
I mean we should not provide ability to enable dashbaords in helm chart, if it doesn't work without dashboard json modification.
Let's close this issue as duplicate.

**Closed** 2023-05-29 15:50 UTC
Labels: bug, needs-triage

**Comment by scholzj** [comment] 2023-05-29 16:01
> I mean we should not provide ability to enable dashbaords in helm chart, if it doesn't work without dashboard json modification.

The problem is that this **works** for many others. I think the issue is that Grafana is not good with backward compatibility and many different versions are being used by different people among other things as a result of them screwing up with licensing.

**Comment by scholzj** [comment] 2023-05-29 16:04
> I mean we should not provide ability to enable dashbaords in helm chart, if it doesn't work without dashboard json modification.

BTW: You do not have to use it. So if it does not work with your Grafana, you do not need to enable it.
