### ISSUE TITLE
[Bug] Topic operator tries to reach Broker with old IP address

### ISSUE THREAD

**Issue by sburkard** [strimzi/strimzi-kafka-operator#3922] opened 2020-11-05 08:34 UTC
**Describe the bug**
When our **Broker Pods** on OpenShift are **recreated** (for whatever reason), they get a **new IP address**. Sometimes (not sure if this happens every time), from this moment on, the logs get filled with messages that the **topic operator is unable to contact the broker** nodes. 

`[2020-11-05 08:23:51,000] WARN  <etworkClient:721> [dminclient-1] [AdminClient clientId=adminclient-1] Connection to node 2 ([broker-node-hostname]/10.131.2.243:9091) could not be established. Broker may not be available.`

When I ping the logged hostname (...svc.cluster.local), the ping is successful, but it **outputs another destination IP address** than the one in the logs. Therefore, a ping to the logged IP address fails. 

`sh-4.2$ ping [broker-node-hostname].svc.cluster.local
PING [broker-node-hostname].svc.cluster.local (10.131.3.28) 56(84) bytes of data.
64 bytes from [broker-node-hostname].svc.cluster.local (10.131.3.28): icmp_seq=1 ttl=64 time=1.62 ms`

Notice **10.131.2.243** in the logs vs. **10.131.3.28** in the ping. 

So, I suspect that the **topic operator tries to reach the broker with an outdated IP address**. Is this a known problem of our quite old Strimzi version? 

Interesting fact: Kafka Connect has sometimes the same problem. 

**Expected behavior**
That the IP addresses of other pods are correctly resolved.

**Environment (please complete the following information):**
 - Strimzi version: 0.11.4
 - Installation method: YAML files
 - Kubernetes cluster: OpenShift 3.11
 - Infrastructure: On premise

**Comment by scholzj** [comment] 2020-11-05 09:17
This is probably caused by DNS caching which in Strimzi 0.11 used the Java defaults. I think this should now be fixed in #2409 (since 0.17.0).

**Comment by sburkard** [comment] 2020-11-05 10:13
Excellent, thanks. I searched the issues, but not the PRs. 

Yes, Java defaults seem to hold a once successfully resolved IP address forever. Quite strange.

It will take some time until we migrated to a newer version. Feel free to close the issue

**Closed** 2020-11-05 10:13 UTC
Labels: bug, question
