### ISSUE TITLE
[Enhancement]: Support AWS_MSK_IAM auth mechanism for MirrorMaker

### ISSUE THREAD

**Issue by mytxyang** [strimzi/strimzi-kafka-operator#10301] opened 2024-07-04 01:48 UTC
### Related problem

We want to use MirrorMaker to replication data between two AWS MSK cluster, but these MSK clusters only enable IAM auth method, current version cannot support AWS_MSK_IAM auth mechanism for MirrorMaker crds.

### Suggested solution

Add support for AWS_MSK_IAM auth mechanism on MirrorMaker controller.

**Comment by scholzj** [comment] 2024-07-04 07:46
Duplicate of #5473

**Comment by scholzj** [comment] 2024-07-11 16:47
Discussed on the community call on 10.7.2024: Duplicate of #5473. This should be closed.

**Closed by scholzj** 2024-07-11 16:47 UTC
Labels: enhancement, needs-triage
