### ISSUE TITLE
[Docs]: cluster-ip listener

### ISSUE THREAD

**Issue by abh** [strimzi/strimzi-kafka-operator#8778] opened 2023-07-04 19:28 UTC
### Suggestion / Problem

The documentation references a cluster-ip listener, but when I configure my listener with

```
    listeners:
      - name: tls
        port: 9093
        type: cluster-ip
...
```

I get an error applying the manifest saying

```
The Kafka "logs" is invalid: spec.kafka.listeners.type: Unsupported value: "cluster-ip": supported values: "internal", "route", "loadbalancer", "nodeport", "ingress"
```

I was trying to change the listener type because I wanted to add annotations and with type=internal I get this error in the operator logs:

```
2023-07-04 19:27:54 ERROR ListenersValidator:46 - Reconciliation #140(timer) Kafka(ntppipeline/logs): Listener configuration is not valid: [listener tls cannot configure bootstrap.annotations because it is not LoadBalancer, NodePort, Route, Ingress or ClusterIP based listener]
```

**Comment by scholzj** [comment] 2023-07-04 19:33
Please share the full configuration and full operator log.

**Comment by scholzj** [comment] 2023-07-13 16:13
Triaged on 13.7.2023: Should be closed as no additional information was provided and it is not clear form the description what the problem is. Can be reopened if additional information is shared.

**Closed by scholzj** 2023-07-13 16:13 UTC
Labels: documentation, needs-triage

**Comment by Falcondevils** [comment] 2023-12-18 21:31
I am receiving the same weird error using terraform.
│ Error: 1 error occurred:
│       * Kafka.kafka.strimzi.io "kafka cluster name" is invalid: spec.kafka.listeners[1].type: Unsupported value: "cluster-ip": supported values: "internal", "route", "loadbalancer", "nodeport", "ingress"
│
│
│
│   with helm_release.kafkaresource,
│   on redflash-kafka-deployment.tf line 19, in resource "helm_release" "kafkaresource":
│   19: resource "helm_release" "kafkaresource" {



strimzi version: 0.37/0.38
Kafka version: 0.34/0.35
For any combination of above 2 versions, I am receiving this.

The error is very weird:

I have 5 AWS eks clusters with all of them with k8 version 1.25:
Same deployment works fine for 4 of the clusters but for 5th one, i receive the error.
I checked the helm values and they are exactly same.

I can provide more details if needed but the error is very straightforward.

Please help.

**Comment by scholzj** [comment] 2023-12-18 21:34
Do you have up-to-date CRDs installed?

**Comment by thatsdone** [comment] 2023-12-25 03:35
I also had the same issue using kafka operator 0.38.0.

https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator/0.38.0

**Comment by scholzj** [comment] 2023-12-25 11:31
@thatsdone I do not think the output you shared is in anyway helpful. But as you point to a Helm Chart, keep in mind that Helm does not update CRDs when upgrading the Helm Chart. You have to do it manually (that is a general Helm feature, nothing special to do with Strimzi).

**Comment by thatsdone** [comment] 2023-12-26 05:23
@scholzj 
So far as users are using helm to install kafka-operator (offered by Strimzi), it doesn't make sense asking "Do you have up-to-date CRDs installed?" or asking version of the installed CRDs because there is no way to see version of the installed kafka-operator CRDs explicitly.

Anyway I will replace kafka-operator CRDs to 0.39.0 (or 0.38.0).

**Comment by scholzj** [comment] 2023-12-26 12:00
> So far as users are using helm to install kafka-operator (offered by Strimzi), it doesn't make sense asking "Do you have up-to-date CRDs installed?" or asking version of the installed CRDs because there is no way to see version of the installed kafka-operator CRDs explicitly.

Why would it not make sense to ask if you have up-to-date CRDs? You are responsible for the installation/upgrades on your own Kubernetes cluster, so you should know if you did upgrade the CRDs as well or not. Also, you can always get the YAML of the CRD you have installed and diff it against the CRDs YAMLs from the release to see if they are the same or not.

**Comment by Falcondevils** [comment] 2023-12-26 16:38
I am a little bit not able to follow here. So if i update the chart version of strimzi kafka operator and also kafka version in the CRD config, Is that not enough??

As per my understanding, I only use strimzi CRD to install Kafka in k8 and then I can override kafka version in the strimzi CRD.
So my question would be which CRD we are talking about here and how can I compare it?
When I visit the strimzi kafka operator github repo, i donot really see any example CRD with cluster-ip listener?https://github.com/strimzi/strimzi-kafka-operator/tree/main/examples/kafka

**Comment by scholzj** [comment] 2023-12-26 16:43
I think you are mixing custom resources (CRs) and custom resource definitions (CRDs). CRs are where you change the Kafka version. CRDs are what define the structure and the fields in the CRs. And the CRDs are part of every Strimzi release - you can find them among the installation files etc. They typically differ between the releases in newly added fields and options such as the `type: cluster-ip` listeners. 

Helm for whatever reason does not update the CRDs during upgrade although they are part of the Helm Chart. So if you use Helm, you have to update the CRDs manually every time you upgrade the Strimzi version through Helm.
