### ISSUE TITLE
TopicOperator throws an exception on internal topics

### ISSUE THREAD

**Issue by wittwerch** [strimzi/strimzi-kafka-operator#2401] opened 2020-01-15 07:27 UTC
**Describe the bug**
It looks like TopicOperator throws an exception, because Kafka is using internal topics which do not follow the naming convention:

```
[2020-01-15 07:13:45,865] INFO  <opicOperator:474> [oop-thread-0] 4848|periodic -__transaction_state: Reconciling topic __transaction_state, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2020-01-15 07:13:45,869] INFO  <opicOperator:474> [oop-thread-0] 4849|periodic -__consumer_offsets: Reconciling topic __consumer_offsets, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2020-01-15 07:13:45,870] ERROR <opicOperator:1297> [oop-thread-0] Error reconciling KafkaTopic null
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/apis/kafka.strimzi.io/v1beta1/namespaces/dev/kafkatopics. Message: KafkaTopic.kafka.strimzi.io "transaction-state---fa0cab98346cf986a8939b968c35641b71f7ad3b" is invalid: metadata.labels: Invalid value: "__transaction_state": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "__transaction_state": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=kafka.strimzi.io, kind=KafkaTopic, name=transaction-state---fa0cab98346cf986a8939b968c35641b71f7ad3b, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=KafkaTopic.kafka.strimzi.io "transaction-state---fa0cab98346cf986a8939b968c35641b71f7ad3b" is invalid: metadata.labels: Invalid value: "__transaction_state": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:510) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:449) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:413) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:819) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:330) ~[io.fabric8.kubernetes-client-4.6.2.jar:?]
	at io.strimzi.operator.topic.K8sImpl.lambda$createResource$0(K8sImpl.java:50) ~[io.strimzi.topic-operator-0.15.0.jar:0.15.0]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-3.7.1.jar:3.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**To Reproduce**
1. Install the Strimzi Cluster Operator (I used https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.15.0/strimzi-cluster-operator-0.15.0.yaml)
2. Create a cluster
3. Use Kafka with transactions (I'm not 100% sure what the app is doing)

**Expected behavior**
I guess no error messages about that :)

**Environment (please complete the following information):**
 - Strimzi version: 0.15.0
 - Installation method: Yaml
 - Kubernetes cluster: OpenShift v3.11.98
 - Infrastructure: on premise

**YAML files and logs**

[report-15-01-2020_08-24-41.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4063533/report-15-01-2020_08-24-41.zip)

**Comment by mike-treadway** [comment] 2020-01-16 14:45
I'm running into this as well for the `_schemas` topic created by the Schema Registry. I'd be just fine if strimzi just left the topic alone and didn't bother syncing it, maybe it just logs a message saying it's skipping it?

**Comment by scholzj** [comment] 2020-01-17 12:26
I think this should be fixed in 0.16.0 (released yesterday) with the PR #2302 - could you doublecheck you still see this problem with it?

**Comment by joekohlsdorf** [comment] 2020-01-22 19:32
Upgrading to 0.16.0 fixed this for me.

**Comment by yaphetsglhf** [comment] 2020-02-25 09:46
helm with version strimzi/strimzi-kafka-operator:0.16.2 still not work. is there something i missed?

**Comment by scholzj** [comment] 2020-02-25 13:01
Are you sure you have the right version? Can you share the whole log of the To including the error and the startup of the TO?

**Comment by yaphetsglhf** [comment] 2020-02-25 13:58
The chart version of strimzi/strimzi-kafka-operator shows 0.16.2. 
Blow is what the error says:
Error: UPGRADE FAILED: failed to create resource: KafkaTopic.kafka.strimzi.io "__consumer_offset" is invalid: metadata.name: Invalid value: "__consumer_offset
": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.c
om', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by scholzj** [comment] 2020-02-25 15:50
Can you provide the whole log please? From the beginning to be able to verify the version?Because this should not be in 0.16.2 and I didn't managed to reproduce it.

**Comment by scholzj** [comment] 2020-02-25 15:51
Or to be more procise, this might be completely different bug since your error is not about labels at all.

**Comment by yaphetsglhf** [comment] 2020-02-26 07:52
Or can you show me a demo about creating internal topic, is there something different in creating with normal ones.

this is a demo how i used with kt:

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: __consumer_offset
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 50
  replicas: 3

I'll record the log latter

**Comment by scholzj** [comment] 2020-02-26 11:22
You cannot create this because `__consumer_offset` isnot a valid Kubernetes name. The name of the KafkaTopic resource has to be valid Kuebrnetes name. You also do not need to create it because KAfka will create this topic automatically.

**Comment by yaphetsglhf** [comment] 2020-02-26 12:32
There is no consumer-offset topic borned with my cluster.  here's my steps.
1. install kafka operator
2. create cluster with resource kind of Kakfa.
3. I check the topics with kubectl get kafkatopics. nope.
4. I check the topics with script bin/kafka-topics.sh, nope.

I guess i missed something.

**Comment by scholzj** [comment] 2020-02-26 12:37
It will get created automatically by Kafka when you start consuming some messages. So you need to add that to your steps.

**Comment by yaphetsglhf** [comment] 2020-02-26 14:42
nope. I produce message to kafka, consumers gets nothing. and when i run `kubectl get kafkatopic`, I can only get the topic i created by yaml.

**Comment by scholzj** [comment] 2020-02-26 14:44
Well, if the consumer doesn't receive anything, it didn't commit any consumed messages. So that is probably why the topic does not exist. I think we need to solve why does your consumer not receive the messages first. Does it get any errors?

**Comment by yaphetsglhf** [comment] 2020-02-26 15:32
but if i create topic consumer-offset manually, everything works fine. So at the beginning, i try to create this topic by kt.

**Comment by yaphetsglhf** [comment] 2020-02-26 15:35
type in the command `kubectl get kafkatopic`, i get the topic `consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a`

**Comment by scholzj** [comment] 2020-02-26 16:57
> but if i create topic consumer-offset manually, everything works fine. So at the beginning, i try to create this topic by kt.

That is not how it normally works. How does your Kafka CR look like? Are all your Kafka nodes running and ready?

> type in the command kubectl get kafkatopic, i get the topic consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a

Yes, That is how it is normally created when Kafka creates the topic automatically.

**Comment by yaphetsglhf** [comment] 2020-02-27 02:30
demo like this:
`{{- if .Values.enabled }}
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
{{- if .Values.kafka.enabled }}
  kafka:
    replicas: {{ .Values.kafka.replicaCount }}
    listeners:
      plain: {}
      tls: {}
    resources:
      requests:
        memory: {{ .Values.kafka.resources.requests.memory }}
        cpu: {{ .Values.kafka.resources.requests.cpu }}
      limits:
        memory: {{ .Values.kafka.resources.limits.memory }}
        cpu: {{ .Values.kafka.resources.limits.cpu }}
    jvmOptions:
      "-XX":
        "UseG1GC": true
        "MaxGCPauseMillis": 20
        "InitiatingHeapOccupancyPercent": 35
        "ExplicitGCInvokesConcurrent": true
        "UseParNewGC": false
      "-Xmx": "1g"
      "-Xms": "1g"
    config:
      default.replication.factor: 3
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      unclean.leader.election.enable: "false"
      auto.leader.rebalance.enable: "false"
      min.insync.replicas: 1
      log.retention.hours: 72
      log.retention.bytes: 10737418240 # 10G
      log.segment.bytes: 1073741824 # 1G
      message.max.bytes: 10485760 # 3M
    storage:
      type: ephemeral
{{- end }}
{{- if .Values.zookeeper.enabled }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicaCount }}
    resources:
      requests:
        memory: {{ .Values.zookeeper.resources.requests.memory }}
        cpu: {{ .Values.zookeeper.resources.requests.cpu }}
      limits:
        memory: {{ .Values.zookeeper.resources.limits.memory }}
        cpu: {{ .Values.zookeeper.resources.limits.cpu }}
    storage:
      type: ephemeral
{{- end }}
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 200m
{{- end }}
`

**Comment by yaphetsglhf** [comment] 2020-02-27 02:32
<img width="466" alt="Screen Shot 2020-02-27 at 10 31 51 AM" src="https://user-images.githubusercontent.com/18364341/75406831-709dd580-594c-11ea-916e-7ada634aa216.png">
demo like this

**Comment by yaphetsglhf** [comment] 2020-02-27 02:36
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    jvmOptions:
      "-XX":
        "UseG1GC": true
        "MaxGCPauseMillis": 20
        "InitiatingHeapOccupancyPercent": 35
        "ExplicitGCInvokesConcurrent": true
        "UseParNewGC": false
      "-Xmx": "1g"
      "-Xms": "1g"
    config:
      default.replication.factor: 3
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      unclean.leader.election.enable: "false"
      auto.leader.rebalance.enable: "false"
      min.insync.replicas: 1
      log.retention.hours: 72
      log.retention.bytes: 10737418240 # 10G
      log.segment.bytes: 1073741824 # 1G
      message.max.bytes: 10485760 # 3M
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 256Mi
          cpu: 200m

**Comment by scholzj** [comment] 2020-02-27 09:33
Right, so ... I think there are some issues in your configuration. First of all, you configure the offset and transaction topics to have replication factor 3:

```yaml
offsets.topic.replication.factor: 3
transaction.state.log.replication.factor: 3
transaction.state.log.min.isr: 2
```

But you deploy only a single Kafka replica. So Kafka will not be able to create it. I think that is the main problem you are having with the consumer. Please have a look here at the example we have for single node clusters: https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-persistent-single.yaml

There are also some other issues you should be careful about:
* `default.replication.factor: 3` means that auto-created topics will not work either because they have again 3 replicas but only 1 broker.
* Single node Zookeeper with ephemeral storage does not work well. It will crash the cluster first time the pod is restarted because it will loose all the data. You should use persistent volume or 3 Zookeeper nodes.
* You give Kafka very little memory - 512Mi. It can probably still live with it, but you should not set -Xmx and -Xms to 1g because that does not fit into your memeory request.

**Comment by yaphetsglhf** [comment] 2020-02-27 10:39
well, some configurations were carried from template file at random, sorry about that. but the replica maybe the key point, i'll check it later. thx so much.

**Comment by yaphetsglhf** [comment] 2020-02-27 17:29
well, it works . thanks buddy. 😎

**Closed** 2020-02-27 23:10 UTC
Labels: bug
