### ISSUE TITLE
KafkaConnect Pending State/CrashLoopBackOffs

### ISSUE THREAD

**Issue by imrohankataria** [strimzi/strimzi-kafka-operator#8609] opened 2023-06-04 22:11 UTC
### Discussed in https://github.com/orgs/strimzi/discussions/8608

<div type='discussions-op-text'>

<sup>Originally posted by **imrohankataria** June  4, 2023</sup>
Hi, I'm having issues running KafkaConnect with Strimzi.
It ran fine initially, but recently started seeing more restarts at POD level. I tried to increase the replicas of KafkaConnect so the connectors won't get affected but then even more frequent **CrashLoopBackOffs**.

Please refer to below timeline -

**ISSUE 1:** Frequent Restarts at POD Level of KafkaConnect
**FIX:** Increased Replicas so connectors won't get affected

**ISSUE2:** Because of Increased Replicas started seeing **CrashLoopBackOffs** / OOMKilled.. etc.
**FIX:** Googled around.. Figured its due to resource utilization, Increased the Resources and stopped seeing OOMKilled but..

**ISSUE3:** 
- The Kafka Connect cluster is still going through multiple RESTARTS, 
- Connectors are in Not ready state (another pain point since there is no direct way to restart connectors manually Im aware of)

**FIX:** Restarted the Strimzi Operator, and then Kafka Cluster 

**ISSUE4**: Not Kafka Clusters are in Pending State from last 12hours
**FIX:** Post the timeline + issue in strimzi repo

**Logs Posted at -**  https://www.logpasta.com/paste/a8279626-1eb6-4fe2-a701-20a6f26d0c13
I see a lot of reconciliation errors, why is that? I read at some places its due to proxy issues, I tried to fix that with HTTP / HTTPS with null values but in the end setup is still not working

**Below is My Kafka Connect Config with Strimzi -** 

`apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: pars-kc
  annotations:
    strimzi.io/use-connector-resources: "true"

spec:
  version: 3.4.0
  replicas: 3
  resources:
    limits:
      cpu: "8"
      memory: "32Gi"
    requests:
      cpu: "4"
      memory: "16Gi"
  bootstrapServers: evh-pars-dev-centralus.servicebus.windows.net:9093
  authentication:
    type: plain
    username: $ConnectionString
    passwordSecret:
      secretName: eventhubssecret
      password: eventhubspassword
  tls:
    trustedCertificates: []

  config:
    group.Id: 123
    offset.storage.topic: strimzi-connect-cluster-offsets
    config.storage.topic: strimzi-connect-cluster-configs
    status.storage.topic: strimzi-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: true
    offset.flush.internal.ms: 10000
    request.timeout.ms: 60000
    kafka.heap.opts: -Xms1G -Xmx2G

  template:
    spec:
      containers:
        - name: pars-kc
          ports:
          - containerPort: 8083
          env:
          - name: HTTP_PROXY
            value: null
          - name: HTTPS_PROXY
            value: null

  build:
    output:
      type: docker
      image: acrparsdevcentralus.azurecr.io/connect:2.2
      pushSecret: acr-secret-2
    plugins:
      - name: snowflake-kafka-connector
        artifacts:
          - type: maven
            repository: https://repo1.maven.org/maven2/
            group: com.snowflake
            artifact: snowflake-kafka-connector
            version: 1.9.2
      - name: kafka-connect-jdbc
        artifacts:
          - type: jar
            url: https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.7.0/kafka-connect-jdbc-10.7.0.jar
            version: 10.7.0
          - type: maven
            repository: https://repo1.maven.org/maven2/
            group: com.microsoft.sqlserver
            artifact: mssql-jdbc
            version: 12.2.0.jre11

  template:
    pod:
      imagePullSecrets:
        - name: acr-secret-2`</div>

**Comment by scholzj** [comment] 2023-06-04 23:00
Duplicate of #8608 

Please do not open the same thing on multiple different places.

**Closed by scholzj** 2023-06-04 23:00 UTC
