### ISSUE TITLE
When KafkaRebalance resource is Ready, it should not transition to due to Kafka Cluster failure

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7953] opened 2023-01-20 23:30 UTC
Once the KafkaRebaance resource is in the Ready state, it should not transition to not ready just because the Kafka cluster moves to _unready_. It is already complete, so there seems to be no value in failing it.

**Comment by scholzj** [comment] 2023-01-26 16:07
Triaged on 26th January 2023: Looks like a bug.

**Comment by kanha-gupta** [comment] 2023-01-27 21:56
Can you provide some direction ? as i am beginner

**Comment by scholzj** [comment] 2023-01-27 22:17
@ppatierno I guess you will be able to guide @kanha-gupta through this

**Comment by kanha-gupta** [comment] 2023-01-28 20:20
@scholzj Hi ! i've tried to resolve this issue, Will improvise according to the directions given in future.
Please review if it solves the bug.
Thanks alot for support :)

**Comment by ppatierno** [comment] 2023-01-30 08:10
@kanha-gupta I have just replied on the PR where @ShubhamRwt did the same.

**Comment by haanhvu** [comment] 2023-02-22 08:59
I'll work on this

**Comment by scholzj** [comment] 2023-02-22 11:47
@haanhvu Thanks. @ShubhamRwt or @ppatierno might be the best guides for this if you need anything.

**Comment by ppatierno** [comment] 2023-02-22 14:45
@haanhvu I think that looking at the closed #7997 is a good start. It was almost done, we added some feedback and requests.

**Comment by prashant235913** [comment] 2023-03-03 17:33
Is this issue open....I want to solve it.

**Comment by haanhvu** [comment] 2023-03-03 17:44
@prashant235913 Yeah please go ahead. I plan to continue this this weekend. But if you want to work on this I'll find something else.

**Comment by prashant235913** [comment] 2023-03-03 17:49
Thanks @haanhvu for the support...As I am Beginner and it Can be my first contribution...How Can i get Some guidance of waht i am supposed to do.

**Comment by haanhvu** [comment] 2023-03-03 18:23
@prashant235913 I think the first step should be setting up the project. You can follow the development guide [here](https://github.com/strimzi/strimzi-kafka-operator/blob/main/development-docs/DEV_GUIDE.md).

If you face a problem during setting up that you don't understand or can't google for, you can ask about it in the Slack channels. If you haven't joined CNCF Slack workspace, get an invite [here](https://communityinviter.com/apps/cloud-native/cncf). If you're already in CNCF Slack, then find and join `strimzi` and `strimzi-dev` channels.

After setting up the project, you can start working on this issue. As @ppatierno pointed out [above](https://github.com/strimzi/strimzi-kafka-operator/issues/7953#issuecomment-1440163194), this issue has already been done partly in #7997. So take a look at that PR to see what to do to complete this issue.

From my brief look at #7997, you'd have to finish the implementation (there's a small refactoring left to do), test the implementation locally to see if it works, and add a unit test to prove it works. See the PR for full details.

Personally, I would try to reproduce this bug locally on the main branch first (before going to #7997). But that's just my personal approach.

If you have questions during finishing this issue, you can ask here or in Slack. But ping @ppatierno and @scholzj and @ShubhamRwt because they understand this issue better than me (I'm new to Strimzi too, just finished 1 PR)

**Comment by prashant235913** [comment] 2023-03-04 07:19
Thanks @haanhvu ...

**Comment by ShubhamRwt** [comment] 2023-03-21 07:12
@prashant235913 Are you planning to work on this?

**Comment by prashant235913** [comment] 2023-03-23 05:54
I am learning it ....But right now I think it'll  take some time for me....You can assign it to someone if needed..
@ShubhamRwt

**Comment by ShubhamRwt** [comment] 2023-04-04 08:06
HI @prashant235913, I will be starting work on it because there are no updates for 2 weeks on this

**Comment by prashant235913** [comment] 2023-04-09 03:48
Carry on @ShubhamRwt ...Sorry for the delay
I am stucked in Octernships tasks...

**Closed** 2023-04-12 12:29 UTC
Labels: bug, good-start
