### ISSUE TITLE
[Bug]: CRD entries "required: []" are not accepted by kubernetes

### ISSUE THREAD

**Issue by andreasgeisslerdt** [strimzi/strimzi-kafka-operator#10582] opened 2024-09-13 14:34 UTC
### Bug Description

When Installing the version 0.43.0 the following CRDs have issues:

- kafkabridges.kafka.strimzi.io
- kafkaconnects.kafka.strimzi.io
- kafkamirrormaker2s.kafka.strimzi.io
- kafkamirrormakers.kafka.strimzi.io
- kafkanodepools.kafka.strimzi.io
- kafkas.kafka.strimzi.io

In all CRDs the additional line "required: []" is not accepted from the CRD source and is removed in the life manifest.

ArgoCD:
<img width="327" alt="image" src="https://github.com/user-attachments/assets/102eb7dd-8639-4ac7-b9ac-658b9c750915">

Diff:
<img width="609" alt="image" src="https://github.com/user-attachments/assets/9beecbc2-cb64-4d82-9a67-aa0196912b12">

### Steps to reproduce

* Install Operator
* Compare Live Manifest with CRD file

### Strimzi version

0.43.0

### Kubernetes version

1.29.1

### Installation method

ArgoCD, helm

**Comment by im-konge** [comment] 2024-09-13 14:57
Hi, this was already resolved in #10492 - until a new release, there is a workaround mentioned in the comments section of the PR.

**Comment by scholzj** [comment] 2024-09-13 20:20
Duplicate of #10541, addressed in #10492.

**Closed by scholzj** 2024-09-13 20:20 UTC
Labels: bug, needs-triage
