### ISSUE TITLE
[Question] Where do I configure resources for strimzi cluster operator when deploying with helm

### ISSUE THREAD

**Issue by oana-s** [strimzi/strimzi-kafka-operator#4000] opened 2020-11-24 15:03 UTC
I use helm to deploy:

> helm repo add strimzi https://strimzi.io/charts/
> helm install strimzi/strimzi-kafka-operator -g

The strimzi cluster operator pod is using most of the time > 70% allocated memory (working sets) and it continously grows over time.
When I check the resources (which I did not configure explicitly) I see

>     Limits:
>       cpu:     1
>       memory:  384Mi
>     Requests:
>       cpu:      200m
>       memory:   384Mi

What do you  suggest? increasing the memory limit should be sufficient? (where can I do this?) Should I worry that the memory continously grows? (I have to monitor it properly but it seems ~5% per day)

Version Strimzi Cluster Operator: strimzi/operator:0.20.0

Thank you!

**Comment by scholzj** [comment] 2020-11-24 15:07
The resources look like the defaults. Whether it is sufficient or not depends at the end on the number of resources it manages and number of namespaces it watches. So it is always a bit individual. One think to watch for are pod restarts caused by it being out of memory.

**Comment by oana-s** [comment] 2020-11-24 15:27
Thank you for the fast reply! 
Indeed those are the defaults when it comes to resouces. I was wondering where I can explcitly specify this in my config?
I have a basic configuration: 1 topic with 10partition, no more than 2 producers at the time and most of the time no activity at all.
I was expecting that memory will decrease at some point/from once in a while, but no - I have to run from within the pod echo 

> 3 > /proc/sys/vm/drop_caches

**Comment by scholzj** [comment] 2020-11-24 16:09
I'm not really an expert on memory in Java TBH. But I'm not sure Java will really give back anything to the system. I guess @tombentley understands it a lot better tham I do and can maybe give a better answer.

> Indeed those are the defaults when it comes to resouces. Can I update the resources whithout causing any damage in a production env?
I have a basic configuration: 1 topic with 10partitions, no more than 2 producers at the time and most of the time no activity at all.

The cluster operator deals with the Kafka clusters, Connect clusters, connectors etc. So it does not really care about the amount of topics or partitions as much as the number of Kafka and Connect clusters or Connectors. If you have just one Kafka cluster, there should be no need to give the operator more resources.

I'm not a Helm user - but you should be able to just override the default resources which are in the `Values` file when installing the Helm Chart. If you change them for a running cluster, it will restart the pod, but in general the operator should not care and just continue where it left of.

**Comment by oana-s** [comment] 2020-12-18 08:23
Thank you Jakub! 
So having just 1 broker, no Kafka Connect clusters, in the last 8 days the Strimzi Cluster Operator has been OOMKiled 4 times
![image](https://user-images.githubusercontent.com/60611170/102591326-24599700-4112-11eb-97ab-f879e9e49197.png)
I checked the Monitor from Azure, I clearly see that it reached the 384M memory and then got restarted 4 times during the last 8days.
Should this behave like this? What can I to avoid it? as I am using the default config...

**Comment by scholzj** [comment] 2020-12-18 12:05
I do not think that is expected. But I guess I do not have any better solution then to increase the memory right now / try to tune the different Java settings such as `-Xmx`.

**Comment by scholzj** [comment] 2021-02-17 23:33
Do you still see this problem with the latest version of Strimzi?

**Comment by oana-s** [comment] 2021-02-18 07:05
With this image quay.io/strimzi/operator:0.21.1, and a limit of 512MB, I have a similar increase but no restart yet (but i only run for 2days now) 
![image](https://user-images.githubusercontent.com/60611170/108318370-036bfb80-71c0-11eb-8d5a-91c27c2dbd48.png)
Thank you for the update, I will keep you posted!

**Comment by oana-s** [comment] 2021-03-08 07:55
I can confirm that it still gets OOMKilled because  it tried to use more memory than its limit
```
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```

**Comment by Excpt0r** [comment] 2021-08-11 09:45
This issue seems to be the same as #4471
I commented in the other issue because the title suits a bit better.
Maybe this can be closed.

**Comment by scholzj** [comment] 2021-10-31 22:11
Closing as duplicate to #4471

**Closed by scholzj** 2021-10-31 22:11 UTC
Labels: question
