### ISSUE TITLE
[Bug] Kafka brokers stuck in a Rolling update loop

### ISSUE THREAD

**Issue by zzvara** [strimzi/strimzi-kafka-operator#3999] opened 2020-11-24 09:39 UTC
**Describe the bug**

From the operator logs we see:

```
2020-11-24 09:24:16 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-0
2020-11-24 09:24:41 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-1
2020-11-24 09:25:11 INFO  AbstractOperator:455 - Reconciliation #54(timer) Kafka(development/kafka-default-development): reconciled
2020-11-24 09:26:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace experimental...
2020-11-24 09:26:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace production...
2020-11-24 09:26:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kube-system...
2020-11-24 09:26:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace staging...
2020-11-24 09:26:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace development...
2020-11-24 09:26:14 INFO  AbstractOperator:217 - Reconciliation #55(timer) Kafka(development/kafka-default-development): Kafka kafka-default-development will be checked for creation or modification
2020-11-24 09:26:16 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-0
2020-11-24 09:26:44 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-1
2020-11-24 09:27:15 INFO  AbstractOperator:455 - Reconciliation #55(timer) Kafka(development/kafka-default-development): reconciled
2020-11-24 09:28:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace experimental...
2020-11-24 09:28:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace production...
2020-11-24 09:28:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kube-system...
2020-11-24 09:28:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace staging...
2020-11-24 09:28:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace development...
2020-11-24 09:28:14 INFO  AbstractOperator:217 - Reconciliation #56(timer) Kafka(development/kafka-default-development): Kafka kafka-default-development will be checked for creation or modification
2020-11-24 09:28:16 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-0
2020-11-24 09:28:46 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-1
2020-11-24 09:29:18 INFO  AbstractOperator:455 - Reconciliation #56(timer) Kafka(development/kafka-default-development): reconciled
2020-11-24 09:30:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace experimental...
2020-11-24 09:30:13 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace production...
2020-11-24 09:30:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kube-system...
2020-11-24 09:30:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace staging...
2020-11-24 09:30:14 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace development...
2020-11-24 09:30:14 INFO  AbstractOperator:217 - Reconciliation #57(timer) Kafka(development/kafka-default-development): Kafka kafka-default-development will be checked for creation or modification
2020-11-24 09:30:16 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-0
```

Kafka brokers get restarted every ~2 minutes.

**To Reproduce**
1. Install Operator as:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: kube-system
spec:
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.20.0
  releaseName: strimzi
  forceUpgrade: true
  values:
    watchNamespaces:
      - development
      - production
      - staging
      - experimental
```

2. Add Kafka cluster as:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-default-development
  namespace: development
spec:
  kafka:
    config:
      auto.create.topics.enable: "true"
      default.replication.factor: 2
      log.retention.check.interval.ms: 300000
      log.retention.hours: 2
      num.partitions: 20
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
    jvmOptions:
      -Xms: 2048m
      -Xmx: 2048m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
    replicas: 2
    storage:
      class: local
      size: 2Gi
      type: persistent-claim
    version: 2.6.0
  zookeeper:
    config:
      ssl.hostnameVerification: false
      ssl.quorum.hostnameVerification: false
    jvmOptions:
      -Xms: 1024G
      -Xmx: 1024G
    replicas: 3
    storage:
      class: local
      size: 1Gi
      type: persistent-claim
  maintenanceTimeWindows:
    - "* * 0-1 ? * SUN,MON,TUE,WED,THU *" // This is a desperate try to switch off Rolling upgrade, did not work.
```

**Expected behavior**
Kafka operator should not Rolling upgrade Kafka brokers.

**Environment (please complete the following information):**
 - Strimzi version: 0.20.0
 - Installation method: HelmRelease (Helm)
 - Kubernetes cluster: Kubernetes 1.17.4
 - Infrastructure: Intel bare metal stack

**YAML files and logs**

Kafka broker logs look the same as:
```
2020-11-24 08:51:58,843 INFO [Controller id=0] Starting replica leader election (PREFERRED) for partitions  triggered by ZkTriggered (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:51:58,851 INFO [Controller id=0] Starting the controller scheduler (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:51:58,864 INFO [RequestSendThread controllerId=0] Controller 0 connected to kafka-default-development-kafka-0.kafka-default-development-kafka-brokers.development.svc:9091 (id: 0 rack: null) for sending state change requests (kafka.controller.RequestSendThread) [Controller-0-to-broker-0-send-thread]
2020-11-24 08:51:58,871 TRACE [Controller id=0 epoch=31] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 0 sent to broker kafka-default-development-kafka-0.kafka-default-development-kafka-brokers.development.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-11-24 08:52:03,852 INFO [Controller id=0] Processing automatic preferred replica leader election (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:03,853 TRACE [Controller id=0] Checking need to trigger auto leader balancing (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:13,889 INFO [Controller id=0] Newly added brokers: 1, deleted brokers: , bounced brokers: , all live brokers: 0,1 (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:13,889 DEBUG [Channel manager on controller 0]: Controller 0 trying to connect to broker 1 (kafka.controller.ControllerChannelManager) [controller-event-thread]
2020-11-24 08:52:13,992 INFO [RequestSendThread controllerId=0] Starting (kafka.controller.RequestSendThread) [Controller-0-to-broker-1-send-thread]
2020-11-24 08:52:13,994 INFO [Controller id=0] New broker startup callback for 1 (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:13,995 INFO [Controller id=0 epoch=31] Sending UpdateMetadata request to brokers Set(0) for 0 partitions (state.change.logger) [controller-event-thread]
2020-11-24 08:52:13,995 INFO [Controller id=0 epoch=31] Sending UpdateMetadata request to brokers Set(1) for 0 partitions (state.change.logger) [controller-event-thread]
2020-11-24 08:52:13,998 TRACE [Controller id=0 epoch=31] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 1 sent to broker kafka-default-development-kafka-0.kafka-default-development-kafka-brokers.development.svc:9091 (id: 0 rack: null) (state.change.logger) [Controller-0-to-broker-0-send-thread]
2020-11-24 08:52:13,998 DEBUG [Controller id=0] Register BrokerModifications handler for Vector(1) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:14,000 INFO [Controller id=0] Updated broker epochs cache: Map(1 -> 4294967939, 0 -> 4294967920) (kafka.controller.KafkaController) [controller-event-thread]
2020-11-24 08:52:14,236 INFO [RequestSendThread controllerId=0] Controller 0 connected to kafka-default-development-kafka-1.kafka-default-development-kafka-brokers.development.svc:9091 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread) [Controller-0-to-broker-1-send-thread]
2020-11-24 08:52:14,301 TRACE [Controller id=0 epoch=31] Received response {error_code=0,_tagged_fields={}} for request UPDATE_METADATA with correlation id 0 sent to broker kafka-default-development-kafka-1.kafka-default-development-kafka-brokers.development.svc:9091 (id: 1 rack: null) (state.change.logger) [Controller-0-to-broker-1-send-thread]
```

After this last TRACE log, brokers receive a SIGTERM.

Zookeepers look good:
```
2020-11-24 09:35:57,073 INFO Processing ruok command from /127.0.0.1:37096 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]
2020-11-24 09:36:06,323 INFO Processing ruok command from /127.0.0.1:37706 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-1]
2020-11-24 09:36:07,066 INFO Processing ruok command from /127.0.0.1:37758 (org.apache.zookeeper.server.NettyServerCnxn) [nioEventLoopGroup-4-2]
2020-11-24 09:36:14,874 INFO Authenticated Id 'CN=cluster-operator,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-1]
```

**Comment by scholzj** [comment] 2020-11-24 11:33
It does not reproduce in my environment. Can you change the logging level in the Cluster Operator to DEBUG and share the full log (it should ideally contain at least two reconciliations rolling the Kafka pods)? Changing the log level should be possible in the Config Map `strimzi-cluster-operator` (just change the `rootLogger.level` to `DEBUG` instead of `INFO`).

**Comment by zzvara** [comment] 2020-11-26 09:23
Hi @scholzj, here are the logs:

```
2020-11-26 09:21:18 DEBUG ZookeeperScaler:185 - The Zookeeper server configuration is already up to date
2020-11-26 09:21:18 DEBUG ZookeeperScaler:142 - Received event WatchedEvent state:Closed type:None path:null from ZooKeeperAdmin client connected to kafka-default-development-zookeeper-0.kafka-default-development-zookeeper-nodes.development.svc:2181,kafka-default-development-zookeeper-1.kafka-default-development-zookeeper-nodes.development.svc:2181,kafka-default-development-zookeeper-2.kafka-default-development-zookeeper-nodes.development.svc:2181
2020-11-26 09:21:18 DEBUG Util:93 - Waiting for Endpoints resource kafka-default-development-zookeeper-client in namespace development to get ready
2020-11-26 09:21:18 DEBUG Util:115 - Endpoints resource kafka-default-development-zookeeper-client in namespace development is ready
2020-11-26 09:21:18 DEBUG Util:93 - Waiting for Endpoints resource kafka-default-development-zookeeper-nodes in namespace development to get ready
2020-11-26 09:21:18 DEBUG Util:115 - Endpoints resource kafka-default-development-zookeeper-nodes in namespace development is ready
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:2702 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Considering manual cleaning of Pods for StatefulSet kafka-default-development-kafka
2020-11-26 09:21:18 DEBUG NetworkPolicyOperator:102 - NetworkPolicy development/kafka-default-development-network-policy-kafka already exists, patching it
2020-11-26 09:21:18 DEBUG NetworkPolicyOperator:168 - NetworkPolicy kafka-default-development-network-policy-kafka in namespace development has been patched
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:855 - STS kafka-default-development-kafka currently has Kafka version KafkaVersion{version='2.6.0', protocolVersion='2.6', messageVersion='2.6', zookeeperVersion='3.5.8', isDefault=true, unsupportedFeatures='null'}
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:865 - STS kafka-default-development-kafka is moving from Kafka version KafkaVersion{version='2.6.0', protocolVersion='2.6', messageVersion='2.6', zookeeperVersion='3.5.8', isDefault=true, unsupportedFeatures='null'}
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:875 - STS kafka-default-development-kafka is moving to Kafka version KafkaVersion{version='2.6.0', protocolVersion='2.6', messageVersion='2.6', zookeeperVersion='3.5.8', isDefault=true, unsupportedFeatures='null'}
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:879 - Kafka version change: Kafka version=KafkaVersion{version='2.6.0', protocolVersion='2.6', messageVersion='2.6', zookeeperVersion='3.5.8', isDefault=true, unsupportedFeatures='null'} (no version change)
2020-11-26 09:21:18 DEBUG KafkaAssemblyOperator:927 - Kafka.spec.kafka.version unchanged
2020-11-26 09:21:18 DEBUG PvcOperator:102 - PersistentVolumeClaim development/data-kafka-default-development-kafka-0 already exists, patching it
2020-11-26 09:21:18 DEBUG PvcOperator:102 - PersistentVolumeClaim development/data-kafka-default-development-kafka-1 already exists, patching it
2020-11-26 09:21:18 DEBUG PvcOperator:168 - PersistentVolumeClaim data-kafka-default-development-kafka-0 in namespace development has been patched
2020-11-26 09:21:18 DEBUG PvcOperator:168 - PersistentVolumeClaim data-kafka-default-development-kafka-1 in namespace development has been patched
2020-11-26 09:21:18 DEBUG ServiceAccountOperator:102 - ServiceAccount development/kafka-default-development-kafka already exists, patching it
2020-11-26 09:21:18 DEBUG ServiceAccountOperator:35 - ServiceAccount kafka-default-development-kafka in namespace development has not been patched: patching service accounts generates new tokens which should be avoided.
2020-11-26 09:21:19 DEBUG ClusterRoleBindingOperator:111 - ClusterRoleBinding strimzi-development-kafka-default-development-kafka-init does not exist, noop
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:1715 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Reconciling existing Services [kafka-default-development-kafka-bootstrap, kafka-default-development-kafka-brokers] against the desired services
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:1724 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Services [] should be deleted
2020-11-26 09:21:19 DEBUG ServiceOperator:102 - Service development/kafka-default-development-kafka-brokers already exists, patching it
2020-11-26 09:21:19 DEBUG ServiceOperator:102 - Service development/kafka-default-development-kafka-bootstrap already exists, patching it
2020-11-26 09:21:19 DEBUG ServiceOperator:168 - Service kafka-default-development-kafka-brokers in namespace development has been patched
2020-11-26 09:21:19 DEBUG ServiceOperator:168 - Service kafka-default-development-kafka-bootstrap in namespace development has been patched
2020-11-26 09:21:19 WARN  VersionUsageUtils:60 - The client is using resource type 'ingresses' with unstable version 'v1beta1'
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:1804 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Reconciling existing Ingresses [] against the desired ingresses
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:1813 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Ingresses [] should be deleted
2020-11-26 09:21:19 DEBUG AbstractModel:692 - Generating certificates
2020-11-26 09:21:19 DEBUG Ca:205 - cluster-ca: Reconciling kafka broker certificates
2020-11-26 09:21:19 DEBUG Ca:362 - Certificate for kafka-default-development-kafka-0 already exists
2020-11-26 09:21:19 DEBUG Ca:362 - Certificate for kafka-default-development-kafka-1 already exists
2020-11-26 09:21:19 DEBUG AbstractModel:700 - End generating certificates
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:2302 - Validating secret [] with custom TLS listener certificates
2020-11-26 09:21:19 DEBUG ConfigMapOperator:102 - ConfigMap development/kafka-default-development-kafka-config already exists, patching it
2020-11-26 09:21:19 DEBUG ConfigMapOperator:47 - ConfigMap kafka-default-development-kafka-config in namespace development has not been patched because resources are equal
2020-11-26 09:21:19 DEBUG SecretOperator:102 - Secret development/kafka-default-development-kafka-brokers already exists, patching it
2020-11-26 09:21:19 DEBUG SecretOperator:168 - Secret kafka-default-development-kafka-brokers in namespace development has been patched
2020-11-26 09:21:19 DEBUG SecretOperator:111 - Secret development/kafka-default-development-kafka-jmx does not exist, noop
2020-11-26 09:21:19 DEBUG PodDisruptionBudgetOperator:102 - PodDisruptionBudget development/kafka-default-development-kafka already exists, patching it
2020-11-26 09:21:19 DEBUG PodDisruptionBudgetDiff:37 - Ignoring PodDisruptionBudget diff {"op":"remove","path":"/status"}
2020-11-26 09:21:19 DEBUG KafkaSetOperator:102 - StatefulSet development/kafka-default-development-kafka already exists, patching it
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/revisionHistoryLimit"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/metadata/annotations/strimzi.io~1generation"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/failureThreshold"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/periodSeconds"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/livenessProbe/successThreshold"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/failureThreshold"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/periodSeconds"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/readinessProbe/successThreshold"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/resources"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/terminationMessagePath"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/containers/0/terminationMessagePolicy"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/dnsPolicy"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/restartPolicy"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/serviceAccount"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/template/spec/volumes/3/configMap/defaultMode"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/volumeClaimTemplates/0/spec/volumeMode"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/spec/volumeClaimTemplates/0/status"}
2020-11-26 09:21:19 DEBUG StatefulSetDiff:86 - StatefulSet development/kafka-default-development-kafka ignoring diff {"op":"remove","path":"/status"}
2020-11-26 09:21:19 DEBUG StatefulSetOperator:305 - Patching StatefulSet development/kafka-default-development-kafka
2020-11-26 09:21:19 DEBUG KafkaSetOperator:168 - StatefulSet kafka-default-development-kafka in namespace development has been patched
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:924 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Upgrade should not be done in this phase
2020-11-26 09:21:19 DEBUG KafkaRoller:203 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Initial order for rolling restart [0, 1]
2020-11-26 09:21:19 DEBUG KafkaRoller:270 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Considering restart of pod 0 after delay of 0 MILLISECONDS
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:3111 - Rolling update of development/kafka-default-development-kafka: pod kafka-default-development-kafka-0 has strimzi.io/generation=0; sts has strimzi.io/generation=0
2020-11-26 09:21:19 DEBUG KafkaAssemblyOperator:3213 - Rolling update of development/kafka-default-development-kafka: pod kafka-default-development-kafka-0 has strimzi.io/custom-listener-cert-thumbprints=; sts has strimzi.io/custom-listener-cert-thumbprints=
2020-11-26 09:21:19 DEBUG KafkaRoller:687 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Creating AdminClient for kafka-default-development-kafka-0.kafka-default-development-kafka-brokers.development.svc.cluster.local:9091,kafka-default-development-kafka-1.kafka-default-development-kafka-brokers.development.svc.cluster.local:9091
2020-11-26 09:21:19 DEBUG KafkaRoller:358 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Pod 0 can be rolled now
2020-11-26 09:21:19 DEBUG KafkaRoller:625 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Rolling pod kafka-default-development-kafka-0
2020-11-26 09:21:19 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-0
2020-11-26 09:21:19 DEBUG PodOperator:71 - Rolling update of development/kafka-default-development-kafka: Waiting for pod kafka-default-development-kafka-0 to be deleted
2020-11-26 09:21:19 DEBUG PodOperator:108 - Pods development/kafka-default-development-kafka-0 exist, deleting it
2020-11-26 09:21:19 DEBUG PodOperator:149 - Pods kafka-default-development-kafka-0 in namespace development has been deleted
2020-11-26 09:21:19 DEBUG Util:93 - Waiting for Pods resource kafka-default-development-kafka-0 in namespace development to get deleted
2020-11-26 09:21:35 DEBUG PodOperator:79 - Rolling pod kafka-default-development-kafka-0 finished
2020-11-26 09:21:35 DEBUG Util:115 - Pods resource kafka-default-development-kafka-0 in namespace development is deleted
2020-11-26 09:21:35 DEBUG PodOperator:88 - Rolling update of development/kafka-default-development-kafka: Pod kafka-default-development-kafka-0 was deleted
2020-11-26 09:21:35 DEBUG KafkaRoller:632 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Waiting for restarted pod kafka-default-development-kafka-0 to become ready
2020-11-26 09:21:35 DEBUG Util:93 - Waiting for Pods resource kafka-default-development-kafka-0 in namespace development to get ready
2020-11-26 09:21:55 DEBUG Util:115 - Pods resource kafka-default-development-kafka-0 in namespace development is ready
2020-11-26 09:21:55 DEBUG KafkaRoller:634 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Pod kafka-default-development-kafka-0 is now ready
2020-11-26 09:21:55 DEBUG KafkaRoller:270 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Considering restart of pod 1 after delay of 0 MILLISECONDS
2020-11-26 09:21:55 DEBUG KafkaAssemblyOperator:3111 - Rolling update of development/kafka-default-development-kafka: pod kafka-default-development-kafka-1 has strimzi.io/generation=0; sts has strimzi.io/generation=0
2020-11-26 09:21:55 DEBUG KafkaAssemblyOperator:3213 - Rolling update of development/kafka-default-development-kafka: pod kafka-default-development-kafka-1 has strimzi.io/custom-listener-cert-thumbprints=; sts has strimzi.io/custom-listener-cert-thumbprints=
2020-11-26 09:21:55 DEBUG KafkaRoller:687 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Creating AdminClient for kafka-default-development-kafka-0.kafka-default-development-kafka-brokers.development.svc.cluster.local:9091,kafka-default-development-kafka-1.kafka-default-development-kafka-brokers.development.svc.cluster.local:9091
2020-11-26 09:21:55 DEBUG KafkaRoller:358 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Pod 1 can be rolled now
2020-11-26 09:21:55 DEBUG KafkaRoller:625 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Rolling pod kafka-default-development-kafka-1
2020-11-26 09:21:55 INFO  PodOperator:65 - Rolling update of development/kafka-default-development-kafka: Rolling pod kafka-default-development-kafka-1
2020-11-26 09:21:55 DEBUG PodOperator:71 - Rolling update of development/kafka-default-development-kafka: Waiting for pod kafka-default-development-kafka-1 to be deleted
2020-11-26 09:21:55 DEBUG PodOperator:108 - Pods development/kafka-default-development-kafka-1 exist, deleting it
2020-11-26 09:21:55 DEBUG PodOperator:149 - Pods kafka-default-development-kafka-1 in namespace development has been deleted
2020-11-26 09:21:55 DEBUG Util:93 - Waiting for Pods resource kafka-default-development-kafka-1 in namespace development to get deleted
2020-11-26 09:22:07 DEBUG PodOperator:79 - Rolling pod kafka-default-development-kafka-1 finished
2020-11-26 09:22:07 DEBUG Util:115 - Pods resource kafka-default-development-kafka-1 in namespace development is deleted
2020-11-26 09:22:07 DEBUG PodOperator:88 - Rolling update of development/kafka-default-development-kafka: Pod kafka-default-development-kafka-1 was deleted
2020-11-26 09:22:07 DEBUG KafkaRoller:632 - Reconciliation #0(watch) Kafka(development/kafka-default-development): Waiting for restarted pod kafka-default-development-kafka-1 to become ready
2020-11-26 09:22:07 DEBUG Util:93 - Waiting for Pods resource kafka-default-development-kafka-1 in namespace development to get ready
```

**Comment by zzvara** [comment] 2020-11-26 09:24
I noticed that it logs `cluster.local` cluster domain but the cluster domain is `sigma`.

**Comment by scholzj** [comment] 2020-11-26 11:42
> I noticed that it logs cluster.local cluster domain but the cluster domain is sigma.

So, did you configured the `KUBERNETES_SERVICE_DNS_DOMAIN` environment variable in the Cluster Operator deployment to `sigma` to override the default settings?

**Comment by scholzj** [comment] 2020-11-26 11:42
I guess you had to otherwise it would not get so far, or?

**Comment by scholzj** [comment] 2020-11-26 14:02
Hmm, so maybe you do not have it set. Because when I set it, it seems to work fine and use the right suffix.

**Comment by zzvara** [comment] 2020-11-26 14:35
@scholzj  Yeah, it is not set.

```
values:
    watchNamespaces:
      - development
      - production
      - staging
      - experimental
```

I see no options to set environment variables in Helm Chart: https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator

Is there a downward API to set is somehow?

Additional question: AFAIK the cluster domain is advertised to each Pod in K8S using environment variables. It should be already there, not?

**Comment by scholzj** [comment] 2020-11-26 15:04
> I see no options to set environment variables in Helm Chart: https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator

I have no clue as I do not use Helm. Maybe the Helm Chart does not allow to configure it right now and you would need to edit the deployment directly.

> Is there a downward API to set is somehow?
> Additional question: AFAIK the cluster domain is advertised to each Pod in K8S using environment variables. It should be already there, not?

No, as far as I know, there is no easy way how to get it (if you know about any, please let me know). I'm just looking if we can autodetect it, but that requires playing with things like doing DNS lookups etc. So I'm curious how reliable it will be.

**Comment by zzvara** [comment] 2020-11-26 15:33
I checked a few things and from the Pod is can not be retrieved easily.

**Comment by zzvara** [comment] 2020-11-26 15:34
I would be nice to be able to overwrite ENV variables from the Helm chart values.

**Comment by scholzj** [comment] 2020-11-26 15:36
I opened #4009 with an attempt for autodetection. Maybe you can try to exec into your Zoo or Kafka pod and try to run `nslookup kubernetes.default | grep "Name:" | sed "s/Name:\skubernetes.default.svc.//"` if it returns the right value for you.

**Comment by scholzj** [comment] 2020-11-26 15:37
> I would be nice to be able to overwrite ENV variables from the Helm chart values.

I think you are able to override some, but not set arbitrary. I'm not sure I will get to it and I do not know Helm well enough to allow setting any env vars. But contributions are always welcome ;-).

**Comment by scholzj** [comment] 2020-12-01 23:00
@zzvara I opened a separate issue #4031 for the Helm Chart since it would be easy to lost in this one. Do you think we can close this one now? Or do you have something else? Thanks

**Closed** 2020-12-02 08:07 UTC
Labels: bug
