### ISSUE TITLE
Assertions for Broker configuration

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#310] opened 2018-03-12 12:55 UTC
It will be nice to have some way to check the configuration of broker in system tests. As a solution, we can execute the command `> bin/kafka-configs.sh --describe --zookeeper localhost:2181 --entity-type brokers` but this command can't return dynamic configurations.

**Comment by tombentley** [comment] 2018-03-12 13:01
The problem is that `bin/kafka-configs.sh` seems to *only* return the dynamic configs, not the static ones, and for these assertions it's the static ones we're interested in. 

Rather than spending time coming up with a way around this now, I propose we defer these extra assertions until strimzi is able to support connection to brokers from outside the k8s cluster, and at that point we can use the Kafka AdminClient to fetch the broker configs and make these assertions.

**Comment by scholzj** [comment] 2018-07-10 07:55
@serrss Was this addressed by #283 ? Or should it still remain open?

**Comment by serrss** [comment] 2018-07-24 14:38
@scholzj This is another type of assertions that we still need to implement

**Comment by scholzj** [comment] 2020-09-10 17:00
Reviewed on 10th September 2020: @Frawless Is this still valid?

**Comment by Frawless** [comment] 2020-09-10 17:12
I don't think so. In test where we need it we use similar commands for get config of kafka or zk. You can close it.

**Closed** 2020-09-10 17:16 UTC
Labels: cluster operator

**Comment by tombentley** [comment] 2020-09-11 08:10
@Frawless you will need to refactor those assertions which are accessing ZK directly! Maybe those are precisely the same assertions that this issue was about, and the ZK access was the work around?

**Comment by Frawless** [comment] 2020-09-11 08:43
I can see Maros uses ```"/bin/bash", "-c", "bin/kafka-configs.sh --bootstrap-server localhost:9092 --entity-type brokers --entity-name 0 --describe"``` in dynamic configuration tests. Maybe this is exactly what was this about?
