### ISSUE TITLE
Zookeeper Pod being killed, getting 'fsGroup: Invalid value'

### ISSUE THREAD

**Issue by donovanmuller** [strimzi/strimzi-kafka-operator#912] opened 2018-09-28 15:19 UTC
On a local minishift instance with OKD 3.10 I can successfully bring up a cluster using `0.7.0` release. However, after the Zookeeper Pod dies for whatever reason, I'm getting the following events for the StatefulSet when trying to scale the Zookeeper StatefulSet back up:

```
create Pod avaf-dev-cluster-zookeeper-0 in StatefulSet avaf-dev-cluster-zookeeper failed error: pods "avaf-dev-cluster-zookeeper-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group]

create Pod avaf-dev-cluster-zookeeper-0 in StatefulSet avaf-dev-cluster-zookeeper failed error: pods "avaf-dev-cluster-zookeeper-0" is forbidden: no providers available to validate pod request
```

![screen shot 2018-09-28 at 16 54 12](https://user-images.githubusercontent.com/1175891/46217768-2f625a00-c343-11e8-91b6-ba046b9c2271.png)

**Comment by donovanmuller** [comment] 2018-09-28 15:35
The only way to get the cluster back into a health state is to delete the cluster as well as the pvc's and then recreating:

``` console
$ oc delete kafka/xxx-dev-cluster
$ oc delete pvc/...

$ oc create -f xxx-dev-cluster.yml
```

**Comment by scholzj** [comment] 2018-09-29 11:04
You mean that you can deploy the cluster and it works fine as long as the pods are running. But once you stop the pod, you run into this issue? Can you share the exact Minishift version on which it happens?

**Comment by donovanmuller** [comment] 2018-10-01 05:43
```console
$ /minishift version
minishift v1.24.0+8a904d0
```

It seems to happen more if one of the Zookeeper Pods gets deleted or when starting the minishift VM again after stopping. Unfortunately this is not 100% reproducible everytime...

**Comment by donovanmuller** [comment] 2018-10-01 18:27
Just happened again, macOS unexpectedly shutdown and on restart and starting minishift again, now have the same error.

**Comment by jroper** [comment] 2018-11-09 05:19
I'm getting this too, I'm on Linux, minishift v1.26.1+1e20f27, Strimzi 0.8.2.

**Comment by scholzj** [comment] 2019-01-18 09:09
I have never seen this in my Minishift. TBH this looks more like something what breaks inside Minishift when it us not terminated properly. However, in the latest master, I added a posibility to configure the `fsGroup` field for pods: https://strimzi.io/docs/master/full.html#con-customizing-pods-str

I wonder it that could help in your situation.

**Comment by scholzj** [comment] 2019-01-30 21:03
Since I haven't received any further feedback, I will close this issue and assume it is fixed by the templating feature. In case this issue persists, feel free to re-open it or open a new one.

**Closed by scholzj** 2019-01-30 21:03 UTC

**Comment by 0x0000-dot-ru** [comment] 2020-08-04 14:20
This has happened on my system for the third time in the last month. minishift v1.34.2+83ebaab, strimzi 0.18.0

**Comment by pantaoran** [comment] 2020-10-22 11:42
We just had this issue today on OpenShift 4.5. It happened after an upgrade from OCP 4.5.14 to 4.5.15.
It was our experimental cluster with no data, so we removed the whole Kafka setup and let ArgoCD deploy it all fresh, then it worked again.
But if this happens on a cluster with users and data I don't know what to do.

**Comment by scholzj** [comment] 2020-10-22 12:11
I think that this is some issue with when the OCP SCC policies kick in. As far as I know usually just restart later after OCP is up and running helps.

**Comment by chengkuangan** [comment] 2021-05-21 06:53
This is happening to me many times as well. I notice the following patterns on OCP. 
1) New setup AMQ Streams works fine.
2) after few restart of OCP (stop and start of rhpds environment), all of suddent, the fsgroup:0 value is injected into statefulset when i check the yaml content.
3) This is only happens when stop and start happens more than 2-3 times
4) Happens to both zookeeper and broker statefulset

The experience for above is consistent. I have encountered the above many times, countless times, which is repeatable.

After the above happened, the fsgroup problem always comes back even I had removed all the kafka and zookeeper, deleted the project, deleted the amq streams operator. Repeatedly the same problem will be back even the first time reinstall operator and strimzi, once this problem occurred. I had to remove the rhpds, create a new rhpds to continue.... and I have done this many many many times....

**Comment by scholzj** [comment] 2021-05-21 08:14
The `fsgroup: 0` is the default. The stopping and starting does not work properly and screws up the tolling which should inject the correct fsgroup matching your SCC policies. I think it doesn't start the OCP internal components first before starting the other pods. That is at least my understanding. If you wanna stop and start it, it is best to delete the cluster before and start a new one after.

**Comment by chengkuangan** [comment] 2021-12-08 01:27
I observed this only happens when the OCP cluster was shutdown and restarted, as in the case for rhpds. The only way to make the whole thing works again is to delete everything including the AMQ Streams Operator and recreate them again, which is not desired. This should be the expected outcome because what happens if production cluster is restarted?

**Comment by chengkuangan** [comment] 2021-12-08 01:29
> I had the same issue happening on an OpenShift cluster. The error message was `0 is not an allowed group`. The fix was to add
> 
> ```
>     template:
>       pod:
>         securityContext: { }
> ```
> 
> to both the kafka and the zookeeper config as described in the [Strimzi Documentation](https://strimzi.io/docs/operators/latest/using.html#type-PodTemplate-reference). This uses the OpenShift default. It's also possible to define `fsGroup` and `runAsUser` specifically, but that was not needed in my case.

My experience, this is temporary fix, after running the cluster for a while, the same config will be injected again and cause your zookeeper and broker to restart and failed with the same error again.

**Comment by scholzj** [comment] 2021-12-08 07:46
> I observed this only happens when the OCP cluster was shutdown and restarted, as in the case for rhpds. The only way to make the whole thing works again is to delete everything including the AMQ Streams Operator and recreate them again, which is not desired. This should not be the expected outcome because what happens if production cluster is restarted?

I'm not sure this corresponds to a Kubernetes cluster being restarted. OpenShift is normally responsible for injecting the right security information based on the SCC profile. My understanding of the issue is that as you _unsuspend_ the cluster is that not everything there happens in the right order and OCP does not inject the right context into the Pods when they are _unsuspended_.

**Comment by rareddy** [comment] 2022-03-16 17:45
I have been running into this issue for last week with OSD clusters, after resuming from hibernation I see the above `fsGroup` invalid error and fails to create the StatefulSets. 

What worked for me is restarting the Strimzi Operator, the error goes away.

**Comment by ntnchrrn07** [comment] 2022-09-07 07:50
> I have been running into this issue for last week with OSD clusters, after resuming from hibernation I see the above `fsGroup` invalid error and fails to create the StatefulSets.
> 
> What worked for me is restarting the Strimzi Operator, the error goes away.

I have observed the same issue on an azure cluster that we shutdown periodicly. 

This issue didn't appear consistently on all hibernations times. 

env OCP 4.8
Strimzi from OCP operator catalog 
quay.io/strimzi/operator@sha256:9ea49407a04006d0bddfaaee822adfb95f5857af32ffcee81ba60ce891b07ba8 

What worked for me is restarting the Strimzi Operator
