### ISSUE TITLE
[Question] too old resource version error 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3479] opened 2020-08-07 15:23 UTC
We are running Amazon EKS version: v1.15.11-eks and using strimzi 0.19. 

I'm seeing a new error that I haven't seen before below. The cluster seems to be in good health besides the cluster operator restarting. 12 restarts in 3 days or so.  The error occurs every 2 minutes or so. 

Any ideas? The cluster operator is watching all namespaces. 

```
k -n NAMESPACE logs strimzi-cluster-operator-57869945dd-jz64c
```
```2020-08-07 14:59:54 ERROR AbstractOperator:301 - Watcher closed with exception in namespace *
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 114874143 (115069397)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:263) [io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by scholzj** [comment] 2020-08-07 18:49
This sometimes happens as a kind of miscommunication between the Kube API server and the Fabric8 library. Normally, the operator should just reconnect and continue (that should be in the log after the exception) - it should not mean anything significant. But I never saw it happen every 2 minutes so I'm not completely sure how significant it is for you.

**Comment by scholzj** [comment] 2020-09-19 20:53
Someone on Slack linked to this SO question / answer: https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version (for the record, when the answer says that the Fabric8 library does not handle this error, we do it in Strimzi and recreate the watch). With that explanation, I wonder if we can close this now.

**Comment by rogaha** [comment] 2020-10-08 20:49
I've got that as well. and I keep seeing the 
```
2020-10-08 20:44:18 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kafka...
2020-10-08 20:44:28 WARN  AbstractOperator:247 - Reconciliation #14238(timer) Kafka(kafka/kafka-cluster): Failed to acquire lock lock::kafka::Kafka::kafka-cluster within 10000ms.
```

message. How can I restart the cluster controller as recommended by the documentation (https://github.com/strimzi/strimzi-kafka-operator/pull/280/files)?

**Comment by scholzj** [comment] 2020-10-08 23:35
@rogaha Please read this about the lock: https://strimzi.io/docs/operators/latest/full/using.html#what_do_the_failed_to_acquire_lock_warnings_in_the_log_mean

**Comment by arun-blacklane** [comment] 2020-10-21 11:32
Hi,
We are facing this issue as well. Consistently seeing this error in cluster operator.
Any guidance on how we can avoid this, or to identify the root cause for the same?

`2020-10-21 08:05:57 ERROR AbstractOperator:301 - Watcher closed with exception in namespace kafka
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 36981024 (39225511)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:263) [io.fabric8.kubernetes-client-4.6.4.jar:?]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [com.squareup.okhttp3.okhttp-3.12.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by scholzj** [comment] 2020-10-21 11:35
Have you read the responses above? For example the one with link to https://stackoverflow.com/questions/61409596/kubernetes-too-old-resource-version?

**Closed** 2020-10-21 11:35 UTC
Labels: question

**Comment by arun-blacklane** [comment] 2020-10-21 11:58
@scholzj 
I went through the conversations.
For us when we see this error cluster operator reconnects and proceeds.

From the discussion it seems like k8s throws this error for watch when asked resourceVersion is old. And strimzi will recreate the watch. 
Question is more towards, if we get this error frequently, is there something that we can do to mitigate that, or can we assume that this is the expected behaviour and we are not loosing anything specific in functionality.

**Comment by scholzj** [comment] 2020-10-21 12:06
I think it depends what do you mean with frequently. But I think these are expected.

**Comment by arun-blacklane** [comment] 2020-10-21 12:34
In the current setup, we are seeing it atleast once in an hour.
Instance we saw it today:
`2020-10-21 08:48:08  
2020-10-21 09:18:38 
2020-10-21 09:35:51 
2020-10-21 09:57:16 
2020-10-21 10:09:37 
2020-10-21 10:54:18  
2020-10-21 11:27:53 
2020-10-21 12:17:48`

**Comment by scholzj** [comment] 2020-10-21 14:11
I think it depends how busy your cluster is in general.
