### ISSUE TITLE
Allow the ability to specify sidecar or additional containers for KafkaCluster

### ISSUE THREAD

**Issue by Sam-Kramer** [strimzi/strimzi-kafka-operator#5458] opened 2021-08-19 20:51 UTC
**Is your feature request related to a problem? Please describe.**
I need to run a sidecar container alongside the Kafka cluster instances, to collect metrics (for our in-house metric system) and various other tasks. I'd argue while vague, it is quite common of many operators to allow individuals to specify their own sidecars (or containers) to allow for weird/custom requirements. 

**Describe the solution you'd like**
Allow the ability to specify sidecar or additional containers for KafkaCluster inside the KafkaClusterSpec.

**Describe alternatives you've considered**

**Additional context**
Happy to do the PR myself, asking before writing in-case the feature is denied.

**Comment by scholzj** [comment] 2021-08-19 21:08
Speaking for myself and not necessarily for other maintainers, I'm not sure this is something I would want to support. This is something what will make it very hard to _support (help)_ users running it. It also opens quite high degree of complexity for things such as sharing volumes, configs, environment variables, resources, networking, etc. So it is not about opening a single PR but rather about maintaining it as well. Having a strong use-case why _many users_ need this feature and how will they use it would be also helpful - especially to clarify what exactly does a sidecar mean.

The best way to proceed would be to either write a [proposal](https://github.com/strimzi/proposals) or maybe come to discuss it to our [community meetings](https://github.com/strimzi/strimzi-kafka-operator#strimzi-community-meetings) (but next week a lot of maintainers are away ... so maybe it is not the best one to discuss it. They should be back for the one afterwards).

Out of curiosity, what kind of custom metric collection do you need that cannot be done remotely as well?

**Comment by Sam-Kramer** [comment] 2021-08-24 12:59
Hey @scholzj I appreciate the fast response!

I think your sentiment makes sense, I'll draft a proposal with much more details on this could make sense.

**Comment by juergenhemelt** [comment] 2022-03-24 14:18
If using OPA authorizer It could be beneficial to have an instance of OPA deployed as a sidecar with each broker. This could be achieved through this feature.

**Comment by scholzj** [comment] 2022-03-31 14:07
Closing as a duplicate of #2976

**Closed by scholzj** 2022-03-31 14:07 UTC
Labels: enhancement
