### ISSUE TITLE
Strimzi kafka operator pod getting evicted EmptyDir volume "strimzi-tmp" exceeds the limit

### ISSUE THREAD

**Issue by nokernel** [strimzi/strimzi-kafka-operator#5579] opened 2021-09-17 13:46 UTC
**Describe the bug**
Strimzi kafka operator pod getting evicted `Usage of EmptyDir volume "strimzi-tmp" exceeds the limit "1Mi".`

Related to https://github.com/strimzi/strimzi-kafka-operator/pull/5375

**To Reproduce**
1. Create kafka clusters that can't be scheduled ( causing alot of java error in operator logs )
2. Wait

**Expected behavior**
Allow customisation of strimzi-tmp limit

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.19.1

**Comment by scholzj** [comment] 2021-09-17 14:37
Can you get the content of the directory as it evolves over the time (at least listing the files)? Or provide more exact steps to reproduce it? Because the ones you have there are very generic and do not seem to do anything for me (maybe you need to explain what you did so that it cannot be scheduled).

In general, for the operator, you can increase the directory size just by editing the deployment.

**Comment by nokernel** [comment] 2021-09-17 15:23
I will try to get more info on what is filling up the tmp mount, maybe that will uncover another issue.

**Comment by sknot-rh** [comment] 2021-09-21 09:13
Having a reproducer would be helpful. I created the Kafka cluster with invalid configuration, CO logs are full of errors, but the content of the `tmp` mount does not change.

**Comment by mdharper** [comment] 2021-09-23 19:30
I've run into the same issue today with a KafkaConnect resource. It looks like the JDBC Connector/JTDS driver uses the temp directory on its own:
`drwxr-xr-x 2 kafka root       60 Sep 23 19:22 hsperfdata_kafka
-rw-r--r-- 1 kafka root 77426688 Sep 23 19:23 jtds10409044170123727212.tmp
-rw-r--r-- 1 kafka root 36978914 Sep 23 19:22 jtds6814623151674711811.tmp
drwxr-xr-x 2 kafka root       40 Sep 23 19:22 kafka
-rw-r--r-- 1 kafka root      960 Sep 23 19:22 strimzi-connect.properties`

It might be that I'm seeing a lot more volume and that's the trigger. Has the use of strimzi-tmp changed in recent operator versions?

**Comment by scholzj** [comment] 2021-09-23 19:36
What is JTDS driver? Does it have some way to tell it how much stuff should it create? I guess we can in theory make the size configurable. But creating (fairly big) random files in `/tmp` is always asking for trouble.

**Comment by mdharper** [comment] 2021-09-23 19:42
I'd agree with that.

jTDS is an open source Sybase/MS SQL driver. I'm using it for the former, since viable driver options that play well with Sybase/JDBC are hard to come by. 
It appears that the default behavior is mentioned in [a comment here](https://sourceforge.net/p/jtds/discussion/104389/thread/13a99249/). I would guess that the concurrent connections and high volume are the trigger, here. 

Would a pod template on the KC resource be an option for overriding the default 1MB size?

**Comment by scholzj** [comment] 2021-09-23 19:45
> Would a pod template on the KC resource be an option for overriding the default 1MB size?

Well, we would need to add support to override this in the custom resources. This is a bit different from the original issue here which was about the operator => you deploy the operator so you can easily edit the deployment and change the value. For operands it is more complicated as such option needs to be added to the operator / CRDs.

**Comment by mdharper** [comment] 2021-09-23 20:05
Noted. Thanks for the quick responses. I realize this is a different issue from the operator tmp directory, but I think perhaps allowing the size to be overridden, or possibly allowing the mapping strimzi's temp directory to something other than /tmp might be useful. Most Java components should be better behaved, but unfortunately that doesn't seem to be the case.

I'm going to poke at this legacy driver and see if I can get it to behave in a more rational way in the meantime.

**Comment by scholzj** [comment] 2021-09-23 20:27
Can you please open a new bug or enhancement issue for this? I think we should track it separately since they are different problems. I will try to have a look to make it configurable when I have some time.

**Comment by zzztimbo** [comment] 2021-11-03 17:43
We're seeing the same issue with the `/tmp` dir filling up in the Strimzi operator pod. 


`k describe po strimzi-cluster-operator-5dc46458b9-254q8 `
```
...
Status:               Failed
Reason:               Evicted
Message:              Usage of EmptyDir volume "strimzi-tmp" exceeds the limit "1Mi". 
...
```

Here is a listing of `/tmp` https://gist.github.com/zzztimbo/401c22ded4fbcc1eb8502b75af58dfcf

We see a ton of cruise control files. I don't know how to view the contents of the file. 

```
[strimzi@strimzi-cluster-operator-5dc46458b9-4fnsf tmp]$ cat io.strimzi.operator.cluster.operator.resource.cruisecontrol.CruiseControlApiImpl1187959107707146695ts
0Y08�~0�*�H��   *�H��
0+L��.��͚w��/��W"�' 0
        0       `�He**���2N���ڧyÀ���<h�ƶ1=�֭o*��<_d��|�����      ��)#�b�����ab��%�*D�p�<�{��
                                                                                           T�Ԃ�[6���A���X��%����
��SW����و���&�Q�A������7��S�Ď��Y���:X���5����  4ӷ���Q��$.hy����`�      ���0�{GI��|1O"�x�s޳�k�C�L�      �       Y�e�S�C�Ԃқ�-�@uQ�1K��.����'�1�{Q�
                            ��N;�2u�����k�ԭ.�是�٤��r�����t
Ӈ�o���lܷ�ϧl�%>zڞlH\�H$1Y������N��idV�4���\���X�)�!K��=�/�@�#J�If��.��hFui�r6��v@y�1P���l�����Ф��g��Ǽ������(�c+�ݭQ����A8�� A���1|��o����&���㢐x��5�D��A5E�@ջֽ��S��8���åƤl|\���^"��|"Fb_��Ȅ�6x���'IZ��X^�oUc��e����`.;�����(6�     �|��_J)-o��K��HTM�%�:*ǆ:id��S�G�������GffJsM��p�72�(��^P�)��.��!���<tz�:�O���y��F/k�8W�
�&�,��9��*�;_
             ��=��0��*nRJgv�ԯ?��7C�X��+)�]kd��9��ĭ
                                                  �������a�*�iǵ�;^3����"? g}�M��)ی��`�����a���a�<e�ޙ�p�3��
��0���ᬺ�o�AX�                                                                                              }�
ֱ��δk�ux��:���Ta����    �
1��ج��`��ۓ�u~��E4�z+�u�H1sA�c�\"S=�c@
p��l�L+sk�����ܕ��l8�aA܅��R.����-DU{6k�i��\M$!@fAt��qX���g,g��� ��Jb[x8�͵~q����lĦ�i�XH.�eao� ��x�(���4:�zHM��>�e
kj[I+���U���NS^��%��3r��k]>4���b�*& �+|���Y�����`@R�]R ���                                                     ��q���<��'E���lz�Z�
                                    �n^��s�CuS��Z���y�I��aȎ��se���{ޓ��X;���҈�Gnrz�N�@3��}�4^tfI5ʽ��C�=�j.ŭ!�~Ol���_J��f��!!����#���QҬ�o�_�����������02Ị�
                                                                                                                                                       �1�@�F�L�&b\Z8T{�gO��K(�x���Xۂ)#�����a��1k���L�\�
                                 k����NI�c���D���7n�߹w�ϫޜ�L�h�F&��Gǒ+��Ҽ9�m=}�8@�-��Km���;�Әd���T�)����D�g���+c�8^.=�w��30d��0>0!0      +쌏�1�Ǝ��F�&0�kw�Hn���̗�ԃĺl5��O��
```

**Comment by scholzj** [comment] 2021-11-03 17:51
@zzztimbo What version of Strimzi are you using?

@kyguy @ppatierno @tomncooper Can you check if CC properly cleans the certificate stores?

**Comment by zzztimbo** [comment] 2021-11-03 17:53
@scholzj we are using version `0.26.0`

**Comment by kyguy** [comment] 2021-11-03 18:18
>  Can you check if CC properly cleans the certificate stores?

I'll take a look!

**Comment by kyguy** [comment] 2021-11-03 21:13
> Can you check if CC properly cleans the certificate stores?

@scholzj Argh this is my fault, I added the call to create the tmp file here [1] but I never added any calls to delete it. I'll submit a PR to fix this!

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java#L50

**Comment by tvollstaedt** [comment] 2021-11-05 10:15
Same issue here. Any workarounds known?

**Comment by scholzj** [comment] 2021-11-05 10:19
You can just edit the deployment YAML and increase the size of the storage.

**Comment by tvollstaedt** [comment] 2021-11-05 10:21
> You can just edit the deployment YAML and increase the size of the storage.

Thanks, but I'm using the helm chart. I don't see a compatible option in the values.yaml. Any other way?

**Comment by scholzj** [comment] 2021-11-05 10:23
Can't you still edit the deployment? Sorry if it is stupid question - I'm not a Helm user.

**Comment by tvollstaedt** [comment] 2021-11-05 10:26
> Can't you still edit the deployment? Sorry if it is stupid question - I'm not a Helm user.

Only on the cluster, I'm not aware of any persisted method with helm. Anyway, I guess that's sufficient for now, as we are evaluating Strimzi as part of a spike. Thanks for your quick reply!

**Comment by scholzj** [comment] 2021-11-05 10:28
#5803 adds support for overriding the size in Helm. But it is not in the last release :-/.

**Comment by scholzj** [comment] 2021-11-06 19:01
@zzztimbo The `io.strimzi.operator.cluster.operator.resource.cruisecontrol.CruiseControlApiImpl*` files should be fixed by #5836. I also opened #5851 for the `io.strimzi.operator.cluster.operator.resource.ZookeeperScaler*` files. 

That leaves the `io.strimzi.operator.common.DefaultAdminClientProvider*` files unaccounted for. I so far failed to reproduce them. Do you remember doing anything special with the Kafka configuration or something like that?

**Comment by zer0stars** [comment] 2021-12-29 00:39
Having this error as well.

**Comment by scholzj** [comment] 2021-12-29 07:23
@zer0stars If you can see this after the fixes mentioned above (i.e. with 0.27.0), it owuld be great if you can provide more details. Thanks.

**Comment by Lykos84** [comment] 2022-01-12 20:40
@scholzj - I'm just starting out on using Strimzi to test containerization in our environments, and I'm seeing this same isseue on any container deployed with the exception of the strimzi-cluster-operator. This is because I set the tmpDirSizeLimit value to 100Mi in the helm deployment. However, despite what's said in [#5804](https://github.com/strimzi/strimzi-kafka-operator/pull/5804), this does not seem to allow any configuration of /tmp for containers other than strimzi-cluster-operator. I can't get the entity-operator, Zookeeper, or Kafka to stay up longer than about a minute before Kubernetes evicts the pods. It also doesn't seem to be isolated to "strimzi-tmp" but also other tmp volumes such as strimzi-to-tmp, etc.

- Strimzi Version: 0.27.0
- Kubernetes version: 1.20.13_1563
- Kafka cluster deployment: Ephemeral example from the github repo: https://github.com/strimzi/strimzi-kafka-operator/blob/main/packaging/examples/kafka/kafka-ephemeral.yaml
- Installation method: Helm

In the helm values.yaml I have tmp Dir size set to 100Mi
`tmpDirSizeLimit: 100Mi`

When I exec into one of the containers, I can see this attach-tools-1.10.3.jar in the /tmp dir, which by itself violates the 1Mi default, so I'm not sure how it would even work with the default value. Does that file not always get deployed to these containers?

```
total 3.1M
-rwxrwxrwx 1 root  root 2.9M Jan 12 17:05 attach-tools-1.10.3.jar
drwxr-xr-x 2 kafka root   60 Jan 12 17:05 hsperfdata_kafka
-rwxrwxrwx 1 root  root 221K Jan 12 17:05 javaagent-loader-1.3.37.jar
drwxr-xr-x 2 kafka root   80 Jan 12 17:04 zookeeper
-rw-r--r-- 1 kafka root  991 Jan 12 17:05 zookeeper.properties
-rw-r--r-- 1 kafka root 1.5K Jan 12 17:04 zookeeper.properties.bak
-rw-r--r-- 1 kafka root  335 Jan 12 17:05 zookeeper.properties.dynamic.700000000
```

**Comment by scholzj** [comment] 2022-01-12 23:46
@Lykos84 That does not seem to be part of neither Strimzi nor ZooKeeper. So I guess the question you need to look into first is how and why did it got there. I guess this might be some tooling you use?

**Comment by Lykos84** [comment] 2022-01-13 15:09
Thanks for that! You were right, our monitoring was injecting this jar into /tmp. That being said, it does still expose that the variable tmpDirSizeLimit does not seem to be honored by all pods.

**Comment by scholzj** [comment] 2022-01-13 15:43
1) WDYT it is not being honored by all pods?
2) What `tmpDirSizeLimit` variable are you talking about?

**Comment by Lykos84** [comment] 2022-01-13 16:19
1. With tmpDirSizeLimit set to 100Mi, as mentioned above, strimzi-kafka-operator shows this amount, as expected:
`  volumes:
    - name: strimzi-tmp
      emptyDir:
        medium: Memory
        sizeLimit: 100Mi`

 I see this in my entity-operator pod config:
`    - name: strimzi-to-tmp
      emptyDir:
        medium: Memory
        sizeLimit: 1Mi`
I think this is a bug because in [#5789](https://github.com/strimzi/strimzi-kafka-operator/issues/5789) a bug was identified in 0.26.0 that resulted in tmpDirSizeLimit (a variable used to control the size of emptyDir volumes for /tmp) not applying to things like the entity-operator, this was closed by [#5804](https://github.com/strimzi/strimzi-kafka-operator/pull/5804)  and, from what I understand, was applied to the 0.27.0 release. This leads me to believe that tmpDirSizeLimit is not applying everywhere it should. Am I understanding the scope of this variable incorrectly?

2. [strimzi-cluster-operator's yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/release-0.27.x/packaging/helm-charts/helm3/strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml) there is a reference to tmpDirSizeLimit:
`      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.tmpDirSizeLimit }}`
I also see this referenced in the [Kafka CRD](https://github.com/strimzi/strimzi-kafka-operator/blob/release-0.27.x/packaging/helm-charts/helm3/strimzi-kafka-operator/crds/040-Crd-kafka.yaml),
`                            tmpDirSizeLimit:
                              type: string
                              pattern: ^([0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                              description: Defines the total amount (for example `1Gi`) of local storage required for temporary EmptyDir volume (`/tmp`). Default value is `1Mi`.`

**Comment by Lykos84** [comment] 2022-01-13 17:24
Ok, after some investigation internally, and a great tutorial on reading the documentation from a friend here at work, documentation [here](https://strimzi.io/docs/operators/latest/using.html#type-PodTemplate-schema-reference) we realized that the tmpDirSizeLimit should be applied at the kafka spec level as a variable under template. For example:
```
spec:
  kafka:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
```
This solved our issue. I have no idea if that helm chart value I mentioned before is supposed to apply to all pods that use the pod template, but now that I understand how this functions at the pod template level, it's definitely applying as I would expect when deploying a kafka resource.

Thanks for your help in sorting all this out, @scholzj.

**Comment by scholzj** [comment] 2022-01-13 17:45
Yeah, sorry. I didn't realized what exactly `tmpDirSizeLimit` you meant. But glad you found the right place.

**Closed** 2022-02-25 21:44 UTC
Labels: bug
