### ISSUE TITLE
[Enhancement] Separate namespace(s) for strimzi resources and kafka

### ISSUE THREAD

**Issue by danjo133** [strimzi/strimzi-kafka-operator#1917] opened 2019-08-22 09:14 UTC
Hello, I have two usecases that I want to solve:

1. Keep content created by users (CRDs) separate from content generated by operators (strimzi)
2. Users push content to multiple namespaces (eg dev, latest, prod or private dev namespaces) but I want to share kafka between at least some of the services to reduce overhead, so I want topic/user entity operators to listen to multiple namespaces and do changes to a cluster in a different one.

From reading the documentation/source, it seems like an entity operator can only listen to one namespace and it will do changes in that same namespace as well.

So, my suggestion is to add a watchedNamespaces parameter to the entity operators like in the cluster operator.

**Comment by scholzj** [comment] 2019-08-25 20:54
Just to keep it for the record - here is the repsonse I provided on Slack and which summarizes why this is not easy:

_The problem with namespaces is that they do not guarantee name uniqueness. So if the Entity OPerator is watching multiple namespaces and you create a topic my-topic in each of them, it needs some special logic to handle it. That is why we so far never implemented it. Similarly, since the topics are bidirectionally synchronized, if you create a topic my-topic2 in Kafka, where should the CRD be created? So to sum it up, it is not completely trivial … and we so far didn’t had the time to properly think it through and have the way which would work for all the different situations._

**Comment by forsberg** [comment] 2019-08-26 07:05
Right, I see the problem.

One possible approach could be that the namespace name is made part of the topic name via a template. This would fit our use case quite well, we have "production" and "latest" namespaces for production could and code that has been pushed automatically via CD. In our case, the topic names written to by tasks in the production namespace are named "production-<TOPIC>", so it would be OK if the namespace always is part of the topic name. Same goes for the user objects. 

That of course leaves topics/users which are global and used by all namespaces. 

That's just my five cents, hopefully adding to your thought process.

**Comment by danxmoran** [comment] 2019-09-11 12:24
@scholzj as a pared-down version of this, do you think it'd be possible to augment the `KafkaUser` spec to accept a field specifying the namespace where the associated user/pass `Secret` should be created? That way even if all the Kafka resources need to live in the same namespace, systems that try to auth as a user created by strimzi can run in a separate space.

**Comment by scholzj** [comment] 2019-09-11 12:43
I think that should be feasible option. There is IMHO actually some other issue which covers that. We just didn't got to it yet to implement it. (as always - any PRs are welcomed!)

**Comment by armisz** [comment] 2021-02-19 16:36
@scholzj Are there meanwhile any news on this? I am looking for a solution where my Kafka cluster runs in namespace A, my KafkaUser resource is located in namespace B, and I would like to have my secret generated into namespace B. I would like to avoid a manual action to copy over the secret from A to B.

**Comment by danjo133** [comment] 2021-02-19 17:20
> @scholzj Are there meanwhile any news on this? I am looking for a solution where my Kafka cluster runs in namespace A, my KafkaUser resource is located in namespace B, and I would like to have my secret generated into namespace B. I would like to avoid a manual action to copy over the secret from A to B.

We created a second operator that deals with this https://github.com/niradynamics/kafka-namespaced-user-topic-operator
It should get an update early next week to make it more stable (new version of kopf)

**Comment by scholzj** [comment] 2022-03-03 17:29
Triaged on 3.3.2020: Duplicate of https://github.com/strimzi/strimzi-kafka-operator/issues/5895 https://github.com/strimzi/strimzi-kafka-operator/issues/1206 -> closing this issue and keeping the other issues since they are separate the TO and UO problematic and solution is not the same.

**Closed by scholzj** 2022-03-03 17:29 UTC
Labels: enhancement
