### ISSUE TITLE
[k8s 1.21] BoundServiceAccountTokenVolume refresh token

### ISSUE THREAD

**Issue by oleksiiprokhorenko** [strimzi/strimzi-kafka-operator#6845] opened 2022-05-20 15:57 UTC
Hi,

Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume feature to beta and enabled it by default. This feature improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that applications that do not refetch service account tokens periodically will receive an HTTP 401 unauthorized error response on requests to Kubernetes API server with expired tokens.

In our kubernetes audit logs we see that system:serviceaccount:kafka-operator:strimzi-cluster-operator still using stale tokens

As per my understanding, that should be fixed by upgrading kafka-operator to latest release Java v9.0.0 and later

**To Reproduce**
install strimzi-kafka-operator in kubernetes cluster with version >= 1.21 and check the kubernetes CloudWatch logs for stale-token:

filter @logStream like 'kube-apiserver-audit'
 | filter ispresent(`annotations.authentication.k8s.io/stale-token`)
 | parse `annotations.authentication.k8s.io/stale-token` "subject: *," as subject
 | stats count(*) as staleCount by subject, `user.username`
 | sort staleCount desc

**Expected behavior**
No errors regarding kafka SA and stale tokens.

**Environment (please complete the following information):**
 - Strimzi version: 0.28.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Amazon EKS

**YAML files and logs**
$ cat strimzi-operator.yml
- name: "Clear for sure chart repo"
  kubernetes.core.helm_repository:
    name: strimzi
    repo_state: absent
  ignore_errors: True

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: strimzi
    repo_url: "https://strimzi.io/charts/"

- name: Upgrade or install Helm chart
  kubernetes.core.helm:
    release_namespace: "kafka-operator"
    create_namespace: "yes"
    release_name: "strimzi"
    chart_version: "0.28.0"
    chart_ref: "strimzi/strimzi-kafka-operator"
    wait: true
    wait_timeout: "300s"
    values:
      watchAnyNamespace: true

  subject   user.username  staleCount
1    system:serviceaccount:kafka-operator:strimzi-cluster-operator   system:serviceaccount:kafka-operator:strimzi-cluster-operator    4988

**Comment by scholzj** [comment] 2022-05-20 16:01
Related to #6804 (and https://github.com/fabric8io/kubernetes-client/issues/2271 & https://github.com/fabric8io/kubernetes-client/issues/2112#issuecomment-1128390799)

**Comment by tyagian** [comment] 2022-09-14 15:34
Do we have fixed it yet or estimate which version should have fix of this?

**Comment by scholzj** [comment] 2022-10-03 21:55
If I understood it correctly, it should have been implemented as part of https://github.com/fabric8io/kubernetes-client/issues/2271 - in Fabric8 6.1.0. That should mean it is fixed in Strimzi 0.31.0 and newer. Can someone affected by this verify if it is the case?

**Comment by KKnapik** [comment] 2023-03-10 16:17
hey Jakub @scholzj , is it related also to changes in 1.24 ? 

> The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Also see [Service account token Secrets](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets).

I am using strimzi 0.26.1 and after upgrade of the cluster (AKS) the service account for operator has no token mounted anymore - 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/30213322/224366765-2332e05a-a19e-482e-8532-fa914fb205c6.png">

Is the operator supports the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) subresource to obtain a token to access the API ? as I do not see a secrets with token anymoore ?

**Comment by scholzj** [comment] 2024-04-18 16:24
Discussed on the community call on 18.4.: Does not seem to be an issue anymore with current versions and can be closed. If not, we need a better explanation what the problem is and what needs to be done

**Closed by scholzj** 2024-04-18 16:24 UTC
Labels: bug, needs-triage
